import json,pathlib
b=pathlib.Path('reference/canon-review');pool={r['guid']:r for f in ['candidate-inventory-dialogue.json','candidate-extra-mentions.json'] for r in json.loads((b/f).read_text(encoding='utf-8'))}
rows=[
('Soana','Explicitly ancient dwarf woman.','e6371ff155ce20d4d9a4bf3d3a7478d7','396b1d46a2cfb1e48b205468d4360ee9','Experimental new route. Untangle her life-linked Abyss-spirit bargain and restore the forest without erasing her age or culpability.','Her destructive protection and sacrifice are core motives; no youthful reskin assumption.'),
('Areelu','Adult mother and long-established researcher; exact current age not required.','4f98da1d37e58474991724bc34cc9bcc','7c4aebf4bbfa61e45b8920868016b4fc','Experimental adult route requested by the user. The original mortal soul inhabiting the Commander is distinct from the grafted remnants; grief may create a maternal projection and identity conflict, but the failed graft does not make him her child or establish attraction.','Develop an authored adult relationship through earned rivalry, grief, anger, desire and choice, with all-path access and nonromantic or hostile outcomes retained.'),
('Jannah Aldori','Adult portrayal inferred from Eagle Watch military service and drinking companionship; no numeric age verified.','56a08e3d9ab1ddb4c81680ae55286e5e','a66a6e34e9aa8d749921acdc7a0ae938','New route through voluntary return after desertion/prison/Condemned outcome.','Preserve death and prison branches; freeing a prisoner cannot purchase romantic consent. Existing exact fate map available in seelah-later-predicates.json.'),
('Yaniel','Explicit old woman and veteran paladin.','cedf416f4d873d0468b01270c7b8eb9e','cbf1a11c8d3ce814595149a211502ad1','New route after genuine Midnight Fane rescue and Radiance recognition.','Fake Yaniel is a separate impersonation. Rescue trauma and possible later death need distinct state handling.'),
('Delamere','Established adult priestess with renowned former career; currently dead.','a20b6707b07208a43928f0a6a9309053','a1a2f1c5e80483649a6d51805a3cd0fb','Experimental autonomous restoration, then a chosen new relationship.','Native compelled undead obedience and hatred cannot be romance consent. Restore agency, not merely a speaking body.'),
('Elyanka Camilary','Explicit old woman, presently mortal; sixteen describes a past event.','13ea42e5da39a694499bb516b8478269','836b49836cd1fb44496ccde3175d74ea','New route on all mythic paths, with a bespoke Trickster introduction beyond her native Lich-centered access.','Her desired undeath is not a condition she already possesses. Preserve fanaticism and Septimus conflict.'),
('Herrax','Adult succubus and brothel madam portrayal; exact age unstated.','1439d3385a918d048be42bf6c66f1cd6','fa4d223f55e2140479ece30fb929ff36','New route around succession at Ten Thousand Delights and independent patronage.','Scars, damaged eye and ragged wings are native features. Brothel service is not personal romantic consent. Coordinate Chivarro/Minagho existing integration.'),
('Mielarah','Adult captain/sorceress portrayal with established career; exact age unstated.','8235006c1e10df244a3467c7b3900f2a','1b4e78245cb3a244588f9ec0fda54ea8','New voyage route addressing Gravedragger curse and choices aboard Starcatcher the Third.','Do not flatten principled captain into innocent heroine: thought-correction and disastrous coercion are also native. Travel outcomes need rescue alternatives.'),
('Shamira','Adult demonic patron/ruler portrayal; exact age unstated.','ab7955d6c7e01d9489f382d77572a9e1','76f6e12133981714eaf235d1bf799144','New intrigue route on all mythic paths through a path-appropriate Harem audience and political stakes, including authored Trickster alternatives.','Telepathy, coercive information demands and dangerous ambition remain; submission or mental intrusion does not prove affection.'),
('Hepzamirah','Adult nephilim commander and archpriestess portrayal; daughter is kinship, not age.','95a274da7d9c72540a386efbdd55a1ed','c1c8de1235d14cc4b85b2454855b90a5','Experimental rescue from post-death imprisonment and an independently chosen anti-Baphomet alliance.','She is mortal nephilim, not ordinary immortal demon. Her revenge pledge is not romance, and gratitude must not be coerced.'),
('Iomedae','Adult-presenting goddess with warrior history, not a mortal age claim.','392b3c9308ec3cc489579720f11ea8d7','48c4c2d62b5217a4fa2f827cfeeddc59','Highly experimental divine audience route on every mythic path; Trickster access and reciprocal personal interest would be new.','Native congratulations or approval do not imply romance. Preserve duty and independence; no mortal recruitment pretense.'),
('Eliandra','Woman/high priestess with hundred-year vigil explicitly established.','0bd02c57a78fd7f4e8b5b379d29280ec','c0dd70f8eb05b8a4fb13342b5507958a','New route on every mythic path from Pulura vigil and rescue, with a bespoke Trickster access route.','Katair is explicitly her fellow leader; reviewed evidence does not establish spouses. Avoid assuming a romance from their shared vigil.'),
('Targona','Adult angel portrayal; precise age unstated.','a528614125b07714db52d9004f36d448','b78adc40541745f438e36a5bc12e95fa','Existing RanRomance route extension through laboratory captivity, altered wing, and recovery; not a new route.','Healing/restoration and personal choice are prerequisites, not payment for rescue. Every-path access, including a bespoke Trickster route, remains to be authored.')]
out=[]
for name,adult,identity,hook,concept,caution in rows:out.append({'name':name,'adult_evidence':adult,'identity_source':pool[identity],'hook_source':pool[hook],'authored_concept':concept,'constraints':caution,'integration_status':('Existing RanRomance Targona route documented in installed readme.txt, with wing/power branches and Aeon/Trickster reactivity; extend rather than duplicate.' if name=='Targona' else 'No native romance established by reviewed evidence; any new route must still be checked against installed expansion content.')})
(b/'additional-candidate-table.json').write_text(json.dumps({'scope':'Local script inventory. Every listed candidate must have an attainable path-appropriate route on all ten mythic paths. No implementation or availability is claimed, and the missing side conversation contributes no evidence. Ember and Aivu remain friendship only.','candidates':out},ensure_ascii=False,indent=2),encoding='utf-8')
lines=['# Additional candidate source table','','Facts below come from local game dialogue; authored access and romance concepts are proposals, not native facts.','Every candidate must receive an attainable, character-appropriate route on all ten mythic paths; a Trickster hook is one required path implementation, not the sole access plan.','Exact numeric ages are not asserted where the game only establishes adult portrayal.','The missing side conversation was not supplied and contributes no evidence.','Ember and Aivu remain strictly nonromantic friendship candidates.','','| Candidate | Adult identity evidence | Native hook | New authored concept and constraint |','|---|---|---|---|']
for r in out:
 a=r['identity_source'];h=r['hook_source'];lines.append('| '+r['name']+' | '+r['adult_evidence']+' '+a['path']+' `'+a['guid']+'` | '+h['path']+' `'+h['guid']+'` | '+r['authored_concept']+' '+r['constraints']+' |')
lines+=['','None of these excerpts establishes a native Commander romance.','Herrax must be coordinated with the existing Chivarro/Minagho integration rather than given a duplicate succession arc.','Other installed romance additions still require a source-level integration check before classifying a route as wholly new.']
(b/'additional-candidate-table.md').write_text('\n'.join(lines)+'\n',encoding='utf-8');print(len(out),'candidates saved')
