"""Reconstruct reviewed native condition fixtures; never run parent initializers."""

import argparse
import hashlib
import json
from pathlib import Path
import re


HERE = Path(__file__).resolve().parent
OUTPUT = HERE.parents[1] / "ParentEndingSourceFixtures.cs"


def read(name):
    return (HERE / name).read_text(encoding="utf-8-sig")


def normalized(text):
    return re.sub(r"\s+", "", text)


def generate():
    provenance = json.loads(read("source-provenance.json"))
    for name, entry in provenance["inputs"].items():
        actual = hashlib.sha256((HERE / name).read_bytes()).hexdigest().upper()
        if actual != entry["sha256"]:
            raise ValueError(f"Changed source evidence: {name}")
    records = json.loads(read("verified-contract.json"))
    if len(records) != 73:
        raise ValueError("Expected the reviewed 73 ordinary/Aeon parent cues")
    aliases = dict(re.findall(r'EtudeConfigurator.New\("([^"]+)", "([0-9a-f]{32})"', read("MinaMain.cs.txt")))
    for filename in dict.fromkeys(entry["file"] for entry in records.values()):
        source = read(filename + ".txt")
        strings = dict(re.findall(r'string (\w+) = "([^"]+)";', source))
        name, guid = re.search(r"BookPageConfigurator.New\((\w+), (\w+)\)", source).groups()
        aliases[strings[name]] = strings[guid]

    def resolve(expression):
        for name, guid in aliases.items():
            expression = expression.replace('"' + name + '"', '"' + guid + '"')
        if re.search(r'"RanRom', expression):
            raise ValueError("Unresolved parent alias in " + expression)
        return expression

    rows = [
        "// <auto-generated />",
        "// Regenerate with: python managed-tests/fixtures/parent-ending-source/generate.py",
        "#nullable disable",
        "using System; using System.Collections.Generic; using System.Linq; using System.Reflection; using Kingmaker.ElementsSystem;",
        "internal static class ParentEndingSourceFixtures",
        "{",
        "internal static Dictionary<string, ConditionsChecker> Build()",
        "{ var result = new Dictionary<string, ConditionsChecker>();",
    ]
    for filename in dict.fromkeys(entry["file"] for entry in records.values()):
        entries = {guid: entry for guid, entry in records.items() if entry["file"] == filename}
        first = next(iter(entries.values()))
        source = read(filename + ".txt")
        definitions = dict(re.findall(r"ConditionsBuilder (conditions\d*) = (.*?);", source, re.S))
        if {key: normalized(value) for key, value in definitions.items()} != {
            key: normalized(value) for key, value in first["all_condition_definitions"].items()
        }:
            raise ValueError("Condition definitions differ from source: " + filename)
        rows.append("{")
        for name, expression in definitions.items():
            rows.append("var " + name + " = " + resolve(expression) + ";")
        rows.append(f'result["{first["page"]}"] = {first["page_condition"]}.Build(null);')
        for guid, entry in entries.items():
            if f'"{guid}"' not in source or f'"{entry["key"]}"' not in source:
                raise ValueError("Cue GUID or original key missing from source: " + guid)
            expression = entry["condition"] or "ConditionsBuilder.New()"
            rows.append(f'result["{guid}"] = {expression}.Build(null);')
        rows.append("}")

    epilogue = read("MinaEpil.cs.txt")
    rows.append("{")
    for name, expression in re.findall(r"ConditionsBuilder (conditions\d*) = (.*?);", epilogue, re.S):
        rows.append("var " + name + " = " + resolve(expression) + ";")
    pair_page = "5c95d8e3fa4f3b44896914987cb04b0b"
    pair_cue = "5787f92575364c1459df8f075676c2db"
    pair = json.loads(read("native-paired.json"))
    if pair[pair_page]["Cues"] != ["!bp_" + pair_cue] or pair[pair_cue]["Conditions"]["Conditions"]:
        raise ValueError("Changed native paired page or cue conditions")
    selector = re.search(r'BookPageConfigurator.For\("' + pair_page + r'"\).SetConditions\((\w+)\)', epilogue).group(1)
    rows.append(f'result["{pair_page}"] = {selector}.Build(null);')
    rows.append("}")
    rows.append(f'result["{pair_cue}"] = ConditionsBuilder.New().Build(null);')
    rows.extend(["return result; }", "internal static ActionList PageActions()", "{"])
    actions = re.search(r"ActionsBuilder onShow = (.*?);", epilogue, re.S).group(1)
    rows.append("return " + resolve(actions) + ".Build(null);")
    rows.append("}")
    rows.append(read("native-builders.cs.txt").rstrip())
    rows.append("}")
    return "\n".join(rows) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify evidence pins and generated file without writing")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("ParentEndingSourceFixtures.cs is not current")
        print("PASS: pinned source evidence and generated fixture match")
    else:
        OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
        print("Generated " + str(OUTPUT))
