"""eng7-l12: contract mutations and save-layout regression, no repo artifacts."""
import copy
import json
from pathlib import Path
import unittest
from tests.structure import without_prose
from tests.story_fixture import fresh_story
from unittest.mock import patch

from expansion import make_expansion
from storylines import engine_eng3_ab
from storylines import engine_q7_l12 as lane
from tools.crossroute_checks import commander_alive, location_staging, world_facts
from tools.crossroute_checks.common import Proof, blocks, verify
from tools import earned_presence_lint


def findings(check, story):
    model = verify.Model(story)
    return check.check(model, list(blocks(model)), Proof(model))



def gate_key(block):
    return (tuple(block.get('Requires', [])), tuple(block.get('Forbids', [])),
            tuple(tuple(group) for group in block.get('AnyGroups', [])))

LIVING_SURFACES = {('anevia.ending_kept', 'end'): [(('anevia.trickster.returned', 'anevia.irabeth_killed_by_commander'),
                                  ('irabeth.trickster.returned', 'irabeth.trickster.cost.dug_out',
                                   'irabeth.trickster.raised_on_record', 'engine.l12.commander_unreturned'),
                                  (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),)),
                                 (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                  ('anevia.committed', 'anevia.closed', 'engine.l12.commander_unreturned'), ()),
                                 (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                  ('anevia.committed', 'anevia.closed', 'anevia.trickster.late_committed',
                                   'engine.l12.commander_unreturned'),
                                  ()),
                                 (('anevia.trickster.returned', 'anevia.trickster.late_committed'),
                                  ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                   'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                  ()),
                                 (('anevia.trickster.returned', 'anevia.trickster.late_committed',
                                   'irabeth.trickster.returned', 'irabeth.present_now'),
                                  ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                   'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                  ()),
                                 (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                  ('engine.l12.commander_unreturned',), ()),
                                 (('anevia.trickster.returned', 'irabeth_dead'),
                                  ('irabeth.trickster.returned', 'anevia.irabeth_killed_by_commander',
                                   'irabeth.trickster.cost.dug_out', 'irabeth.trickster.raised_on_record',
                                   'engine.l12.commander_unreturned'),
                                  (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),))],
 ('anevia.ending_open', 'end'): [(('anevia.trickster.returned', 'anevia.irabeth_killed_by_commander'),
                                  ('irabeth.trickster.returned', 'irabeth.trickster.cost.dug_out',
                                   'irabeth.trickster.raised_on_record', 'engine.l12.commander_unreturned'),
                                  (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),)),
                                 (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                  ('anevia.committed', 'anevia.closed', 'engine.l12.commander_unreturned'), ()),
                                 (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                  ('anevia.committed', 'anevia.closed', 'anevia.trickster.late_committed',
                                   'engine.l12.commander_unreturned'),
                                  ()),
                                 (('anevia.trickster.returned', 'anevia.trickster.late_committed'),
                                  ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                   'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                  ()),
                                 (('anevia.trickster.returned', 'anevia.trickster.late_committed',
                                   'irabeth.trickster.returned', 'irabeth.present_now'),
                                  ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                   'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                  ()),
                                 (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                  ('engine.l12.commander_unreturned',), ()),
                                 (('anevia.trickster.returned', 'irabeth_dead'),
                                  ('irabeth.trickster.returned', 'anevia.irabeth_killed_by_commander',
                                   'irabeth.trickster.cost.dug_out', 'irabeth.trickster.raised_on_record',
                                   'engine.l12.commander_unreturned'),
                                  (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),))],
 ('anevia.ending_unfinished', 'end'): [(('anevia.trickster.returned', 'anevia.irabeth_killed_by_commander'),
                                        ('irabeth.trickster.returned', 'irabeth.trickster.cost.dug_out',
                                         'irabeth.trickster.raised_on_record', 'engine.l12.commander_unreturned'),
                                        (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),)),
                                       (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                        ('anevia.committed', 'anevia.closed', 'engine.l12.commander_unreturned'), ()),
                                       (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                        ('anevia.committed', 'anevia.closed', 'anevia.trickster.late_committed',
                                         'engine.l12.commander_unreturned'),
                                        ()),
                                       (('anevia.trickster.returned', 'anevia.trickster.late_committed'),
                                        ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                         'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                        ()),
                                       (('anevia.trickster.returned', 'anevia.trickster.late_committed',
                                         'irabeth.trickster.returned', 'irabeth.present_now'),
                                        ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                         'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                        ()),
                                       (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                        ('engine.l12.commander_unreturned',), ()),
                                       (('anevia.trickster.returned', 'irabeth_dead'),
                                        ('irabeth.trickster.returned', 'anevia.irabeth_killed_by_commander',
                                         'irabeth.trickster.cost.dug_out', 'irabeth.trickster.raised_on_record',
                                         'engine.l12.commander_unreturned'),
                                        (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),))],
 ('anevia.ending_promised', 'end'): [(('anevia.trickster.returned', 'anevia.irabeth_killed_by_commander'),
                                      ('irabeth.trickster.returned', 'irabeth.trickster.cost.dug_out',
                                       'irabeth.trickster.raised_on_record', 'engine.l12.commander_unreturned'),
                                      (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),)),
                                     (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                      ('anevia.committed', 'anevia.closed', 'engine.l12.commander_unreturned'), ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                      ('anevia.committed', 'anevia.closed', 'anevia.trickster.late_committed',
                                       'engine.l12.commander_unreturned'),
                                      ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.late_committed'),
                                      ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                       'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                      ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.late_committed',
                                       'irabeth.trickster.returned', 'irabeth.present_now'),
                                      ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                       'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                      ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                      ('engine.l12.commander_unreturned',), ()),
                                     (('anevia.trickster.returned', 'irabeth_dead'),
                                      ('irabeth.trickster.returned', 'anevia.irabeth_killed_by_commander',
                                       'irabeth.trickster.cost.dug_out', 'irabeth.trickster.raised_on_record',
                                       'engine.l12.commander_unreturned'),
                                      (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),))],
 ('anevia.ending_parted', 'end'): [(('anevia.trickster.returned', 'anevia.irabeth_killed_by_commander'),
                                    ('irabeth.trickster.returned', 'irabeth.trickster.cost.dug_out',
                                     'irabeth.trickster.raised_on_record', 'engine.l12.commander_unreturned',
                                     'anevia.closed'),
                                    (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),)),
                                   (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                    ('anevia.committed', 'anevia.closed', 'engine.l12.commander_unreturned'), ()),
                                   (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                    ('anevia.committed', 'anevia.closed', 'anevia.trickster.late_committed',
                                     'engine.l12.commander_unreturned'),
                                    ()),
                                   (('anevia.trickster.returned', 'anevia.trickster.late_committed'),
                                    ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                     'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                    ()),
                                   (('anevia.trickster.returned', 'anevia.trickster.late_committed',
                                     'irabeth.trickster.returned', 'irabeth.present_now'),
                                    ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                     'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                    ()),
                                   (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                    ('engine.l12.commander_unreturned', 'anevia.closed'), ()),
                                   (('anevia.trickster.returned', 'irabeth_dead'),
                                    ('irabeth.trickster.returned', 'anevia.irabeth_killed_by_commander',
                                     'irabeth.trickster.cost.dug_out', 'irabeth.trickster.raised_on_record',
                                     'engine.l12.commander_unreturned', 'anevia.closed'),
                                    (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),))],
 ('anevia.ending_survivor', 'end'): [(('anevia.trickster.returned', 'anevia.irabeth_killed_by_commander'),
                                      ('irabeth.trickster.returned', 'irabeth.trickster.cost.dug_out',
                                       'irabeth.trickster.raised_on_record', 'engine.l12.commander_unreturned'),
                                      (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),)),
                                     (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                      ('anevia.committed', 'anevia.closed', 'engine.l12.commander_unreturned'), ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                      ('anevia.committed', 'anevia.closed', 'anevia.trickster.late_committed',
                                       'engine.l12.commander_unreturned'),
                                      ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.late_committed'),
                                      ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                       'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                      ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.late_committed',
                                       'irabeth.trickster.returned', 'irabeth.present_now'),
                                      ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                       'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                      ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                      ('engine.l12.commander_unreturned',), ()),
                                     (('anevia.trickster.returned', 'irabeth_dead'),
                                      ('irabeth.trickster.returned', 'anevia.irabeth_killed_by_commander',
                                       'irabeth.trickster.cost.dug_out', 'irabeth.trickster.raised_on_record',
                                       'engine.l12.commander_unreturned'),
                                      (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),))],
 ('anevia.ending_grief_unanswered', 'end'): [(('anevia.trickster.returned', 'anevia.irabeth_killed_by_commander'),
                                              ('irabeth.trickster.returned', 'irabeth.trickster.cost.dug_out',
                                               'irabeth.trickster.raised_on_record',
                                               'engine.l12.commander_unreturned'),
                                              (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),)),
                                             (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                              ('anevia.committed', 'anevia.closed', 'engine.l12.commander_unreturned'),
                                              ()),
                                             (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                              ('anevia.committed', 'anevia.closed', 'anevia.trickster.late_committed',
                                               'engine.l12.commander_unreturned'),
                                              ()),
                                             (('anevia.trickster.returned', 'anevia.trickster.late_committed'),
                                              ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                               'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                              ()),
                                             (('anevia.trickster.returned', 'anevia.trickster.late_committed',
                                               'irabeth.trickster.returned', 'irabeth.present_now'),
                                              ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                               'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                              ()),
                                             (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                              ('engine.l12.commander_unreturned',), ()),
                                             (('anevia.trickster.returned', 'irabeth_dead'),
                                              ('irabeth.trickster.returned', 'anevia.irabeth_killed_by_commander',
                                               'irabeth.trickster.cost.dug_out', 'irabeth.trickster.raised_on_record',
                                               'engine.l12.commander_unreturned'),
                                              (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),))],
 ('anevia.ending_wife_killed', 'end'): [(('anevia.trickster.returned', 'anevia.irabeth_killed_by_commander'),
                                         ('irabeth.trickster.returned', 'irabeth.trickster.cost.dug_out',
                                          'irabeth.trickster.raised_on_record', 'engine.l12.commander_unreturned'),
                                         (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),)),
                                        (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                         ('anevia.committed', 'anevia.closed', 'engine.l12.commander_unreturned'), ()),
                                        (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                         ('anevia.committed', 'anevia.closed', 'anevia.trickster.late_committed',
                                          'engine.l12.commander_unreturned'),
                                         ()),
                                        (('anevia.trickster.returned', 'anevia.trickster.late_committed'),
                                         ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                          'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                         ()),
                                        (('anevia.trickster.returned', 'anevia.trickster.late_committed',
                                          'irabeth.trickster.returned', 'irabeth.present_now'),
                                         ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                          'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                         ()),
                                        (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                         ('engine.l12.commander_unreturned',), ()),
                                        (('anevia.trickster.returned', 'irabeth_dead'),
                                         ('irabeth.trickster.returned', 'anevia.irabeth_killed_by_commander',
                                          'irabeth.trickster.cost.dug_out', 'irabeth.trickster.raised_on_record',
                                          'engine.l12.commander_unreturned'),
                                         (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),))],
 ('anevia.ending_sacrifice', 'end'): [(('anevia.trickster.returned', 'anevia.irabeth_killed_by_commander'),
                                       ('irabeth.trickster.returned', 'irabeth.trickster.cost.dug_out',
                                        'irabeth.trickster.raised_on_record', 'engine.l12.commander_unreturned'),
                                       (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),)),
                                      (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                       ('anevia.committed', 'anevia.closed', 'engine.l12.commander_unreturned'), ()),
                                      (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                       ('anevia.committed', 'anevia.closed', 'anevia.trickster.late_committed',
                                        'engine.l12.commander_unreturned'),
                                       ()),
                                      (('anevia.trickster.returned', 'anevia.trickster.late_committed'),
                                       ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                        'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                       ()),
                                      (('anevia.trickster.returned', 'anevia.trickster.late_committed',
                                        'irabeth.trickster.returned', 'irabeth.present_now'),
                                       ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                        'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                       ()),
                                      (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                       ('engine.l12.commander_unreturned',), ()),
                                      (('anevia.trickster.returned', 'irabeth_dead'),
                                       ('irabeth.trickster.returned', 'anevia.irabeth_killed_by_commander',
                                        'irabeth.trickster.cost.dug_out', 'irabeth.trickster.raised_on_record',
                                        'engine.l12.commander_unreturned'),
                                       (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),))],
 ('anevia.ending_changed_power', 'end'): [(('anevia.trickster.returned', 'anevia.irabeth_killed_by_commander'),
                                           ('irabeth.trickster.returned', 'irabeth.trickster.cost.dug_out',
                                            'irabeth.trickster.raised_on_record', 'engine.l12.commander_unreturned'),
                                           (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),)),
                                          (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                           ('anevia.committed', 'anevia.closed', 'engine.l12.commander_unreturned'),
                                           ()),
                                          (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                           ('anevia.committed', 'anevia.closed', 'anevia.trickster.late_committed',
                                            'engine.l12.commander_unreturned'),
                                           ()),
                                          (('anevia.trickster.returned', 'anevia.trickster.late_committed'),
                                           ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                            'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                           ()),
                                          (('anevia.trickster.returned', 'anevia.trickster.late_committed',
                                            'irabeth.trickster.returned', 'irabeth.present_now'),
                                           ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                            'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                           ()),
                                          (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                           ('engine.l12.commander_unreturned',), ()),
                                          (('anevia.trickster.returned', 'irabeth_dead'),
                                           ('irabeth.trickster.returned', 'anevia.irabeth_killed_by_commander',
                                            'irabeth.trickster.cost.dug_out', 'irabeth.trickster.raised_on_record',
                                            'engine.l12.commander_unreturned'),
                                           (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),))],
 ('anevia.ending_ascended', 'end'): [(('anevia.trickster.returned', 'anevia.irabeth_killed_by_commander'),
                                      ('irabeth.trickster.returned', 'irabeth.trickster.cost.dug_out',
                                       'irabeth.trickster.raised_on_record', 'engine.l12.commander_unreturned'),
                                      (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),)),
                                     (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                      ('anevia.committed', 'anevia.closed', 'engine.l12.commander_unreturned'), ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                      ('anevia.committed', 'anevia.closed', 'anevia.trickster.late_committed',
                                       'engine.l12.commander_unreturned'),
                                      ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.late_committed'),
                                      ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                       'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                      ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.late_committed',
                                       'irabeth.trickster.returned', 'irabeth.present_now',
                                       'crossroute.irabeth.available'),
                                      ('anevia.committed', 'anevia.closed', 'anevia.trickster.declined',
                                       'anevia.trickster.friends', 'engine.l12.commander_unreturned'),
                                      ()),
                                     (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                      ('engine.l12.commander_unreturned',), ()),
                                     (('anevia.trickster.returned', 'irabeth_dead'),
                                      ('irabeth.trickster.returned', 'anevia.irabeth_killed_by_commander',
                                       'irabeth.trickster.cost.dug_out', 'irabeth.trickster.raised_on_record',
                                       'engine.l12.commander_unreturned'),
                                      (('anevia.trickster.terms_kept', 'anevia.trickster.cost.her_key'),))],
 ('irabeth.ending_lasting', 'returned'): [(('irabeth.trickster.late_committed',),
                                           ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                            'irabeth.trickster.friends', 'anevia_gone', 'ending.wound_closed',
                                            'engine.l12.commander_unreturned'),
                                           ()),
                                          (('irabeth.trickster.late_committed', 'anevia.trickster.returned'),
                                           ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                            'irabeth.trickster.friends', 'ending.wound_closed',
                                            'engine.l12.commander_unreturned'),
                                           ()),
                                          (('irabeth.trickster.late_committed', 'anevia.trickster.returned',
                                            'ending.wound_closed'),
                                           ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                            'irabeth.trickster.friends', 'engine.l12.commander_unreturned'),
                                           ()),
                                          (('irabeth.trickster.late_committed', 'ending.wound_closed'),
                                           ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                            'irabeth.trickster.friends', 'anevia_gone',
                                            'engine.l12.commander_unreturned'),
                                           ()),
                                          (('irabeth.trickster.pen_sent', 'anevia.present_now'),
                                           ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                            'engine.l12.commander_unreturned'),
                                           ()),
                                          (('irabeth.trickster.pen_sent', 'ending.wound_closed', 'anevia.present_now'),
                                           ('irabeth.committed', 'irabeth.closed', 'engine.l12.commander_unreturned'),
                                           ())],
 ('irabeth.ending_lasting', 'living'): [(('irabeth.trickster.late_committed', 'anevia.present_now'),
                                         ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                          'irabeth.trickster.friends', 'anevia_gone', 'ending.wound_closed',
                                          'engine.l12.commander_unreturned'),
                                         ()),
                                        (('irabeth.trickster.late_committed', 'anevia.trickster.returned'),
                                         ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                          'irabeth.trickster.friends', 'ending.wound_closed',
                                          'engine.l12.commander_unreturned'),
                                         ()),
                                        (('irabeth.trickster.late_committed', 'anevia.trickster.returned',
                                          'ending.wound_closed'),
                                         ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                          'irabeth.trickster.friends', 'engine.l12.commander_unreturned'),
                                         ()),
                                        (('irabeth.trickster.late_committed', 'ending.wound_closed',
                                          'anevia.present_now'),
                                         ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                          'irabeth.trickster.friends', 'anevia_gone',
                                          'engine.l12.commander_unreturned'),
                                         ()),
                                        (('irabeth.trickster.pen_sent', 'anevia.present_now'),
                                         ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                          'engine.l12.commander_unreturned'),
                                         ()),
                                        (('irabeth.trickster.pen_sent', 'ending.wound_closed', 'anevia.present_now'),
                                         ('irabeth.committed', 'irabeth.closed', 'engine.l12.commander_unreturned'),
                                         ())],
 ('irabeth.ending_lasting', 'dead'): [(('irabeth.trickster.late_committed', 'anevia.trickster.returned'),
                                       ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                        'irabeth.trickster.friends', 'ending.wound_closed',
                                        'engine.l12.commander_unreturned'),
                                       ()),
                                      (('irabeth.trickster.late_committed', 'anevia.trickster.returned',
                                        'ending.wound_closed'),
                                       ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                        'irabeth.trickster.friends', 'engine.l12.commander_unreturned'),
                                       ()),
                                      (('irabeth.trickster.late_committed', 'crossroute.anevia.available'),
                                       ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                        'irabeth.trickster.friends', 'anevia_gone', 'ending.wound_closed',
                                        'engine.l12.commander_unreturned'),
                                       ()),
                                      (('irabeth.trickster.late_committed', 'ending.wound_closed',
                                        'crossroute.anevia.available'),
                                       ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                        'irabeth.trickster.friends', 'anevia_gone', 'engine.l12.commander_unreturned'),
                                       ()),
                                      (('irabeth.trickster.pen_sent', 'crossroute.anevia.available'),
                                       ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                        'engine.l12.commander_unreturned'),
                                       ()),
                                      (('irabeth.trickster.pen_sent', 'ending.wound_closed',
                                        'crossroute.anevia.available'),
                                       ('irabeth.committed', 'irabeth.closed', 'engine.l12.commander_unreturned'),
                                       ())],
 ('irabeth.ending_lasting', 'gone'): [(('irabeth.trickster.late_committed',),
                                       ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                        'irabeth.trickster.friends', 'anevia_gone', 'ending.wound_closed',
                                        'engine.l12.commander_unreturned'),
                                       ()),
                                      (('irabeth.trickster.late_committed', 'anevia.trickster.returned'),
                                       ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                        'irabeth.trickster.friends', 'ending.wound_closed',
                                        'engine.l12.commander_unreturned'),
                                       ()),
                                      (('irabeth.trickster.late_committed', 'anevia.trickster.returned',
                                        'ending.wound_closed'),
                                       ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                        'irabeth.trickster.friends', 'engine.l12.commander_unreturned'),
                                       ()),
                                      (('irabeth.trickster.late_committed', 'ending.wound_closed'),
                                       ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                        'irabeth.trickster.friends', 'anevia_gone', 'engine.l12.commander_unreturned'),
                                       ()),
                                      (('irabeth.trickster.pen_sent', 'crossroute.anevia.available'),
                                       ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                        'engine.l12.commander_unreturned'),
                                       ()),
                                      (('irabeth.trickster.pen_sent', 'ending.wound_closed',
                                        'crossroute.anevia.available'),
                                       ('irabeth.committed', 'irabeth.closed', 'engine.l12.commander_unreturned'),
                                       ())],
 ('irabeth.ending_open', 'end'): [(('irabeth.trickster.late_committed', 'anevia.trickster.returned'),
                                   ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                    'irabeth.trickster.friends', 'ending.wound_closed',
                                    'engine.l12.commander_unreturned'),
                                   ()),
                                  (('irabeth.trickster.late_committed', 'anevia.trickster.returned',
                                    'ending.wound_closed'),
                                   ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                    'irabeth.trickster.friends', 'engine.l12.commander_unreturned'),
                                   ()),
                                  (('irabeth.trickster.late_committed', 'crossroute.anevia.available'),
                                   ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                    'irabeth.trickster.friends', 'anevia_gone', 'ending.wound_closed',
                                    'engine.l12.commander_unreturned'),
                                   ()),
                                  (('irabeth.trickster.late_committed', 'ending.wound_closed',
                                    'crossroute.anevia.available'),
                                   ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                    'irabeth.trickster.friends', 'anevia_gone', 'engine.l12.commander_unreturned'),
                                   ()),
                                  (('irabeth.trickster.pen_sent', 'crossroute.anevia.available'),
                                   ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                    'engine.l12.commander_unreturned'),
                                   ()),
                                  (('irabeth.trickster.pen_sent', 'ending.wound_closed', 'crossroute.anevia.available'),
                                   ('irabeth.committed', 'irabeth.closed', 'engine.l12.commander_unreturned'), ())],
 ('irabeth.ending_friends', 'end'): [(('irabeth.trickster.late_committed', 'anevia.trickster.returned'),
                                      ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                       'irabeth.trickster.friends', 'ending.wound_closed',
                                       'engine.l12.commander_unreturned'),
                                      ()),
                                     (('irabeth.trickster.late_committed', 'anevia.trickster.returned',
                                       'ending.wound_closed'),
                                      ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                       'irabeth.trickster.friends', 'engine.l12.commander_unreturned'),
                                      ()),
                                     (('irabeth.trickster.late_committed', 'crossroute.anevia.available'),
                                      ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                       'irabeth.trickster.friends', 'anevia_gone', 'ending.wound_closed',
                                       'engine.l12.commander_unreturned'),
                                      ()),
                                     (('irabeth.trickster.late_committed', 'ending.wound_closed',
                                       'crossroute.anevia.available'),
                                      ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                       'irabeth.trickster.friends', 'anevia_gone', 'engine.l12.commander_unreturned'),
                                      ()),
                                     (('irabeth.trickster.pen_sent', 'crossroute.anevia.available'),
                                      ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                       'engine.l12.commander_unreturned'),
                                      ()),
                                     (('irabeth.trickster.pen_sent', 'ending.wound_closed',
                                       'crossroute.anevia.available'),
                                      ('irabeth.committed', 'irabeth.closed', 'engine.l12.commander_unreturned'), ())],
 ('irabeth.ending_unfinished', 'end'): [(('irabeth.trickster.late_committed', 'anevia.trickster.returned'),
                                         ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                          'irabeth.trickster.friends', 'ending.wound_closed',
                                          'engine.l12.commander_unreturned'),
                                         ()),
                                        (('irabeth.trickster.late_committed', 'anevia.trickster.returned',
                                          'ending.wound_closed'),
                                         ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                          'irabeth.trickster.friends', 'engine.l12.commander_unreturned'),
                                         ()),
                                        (('irabeth.trickster.late_committed', 'crossroute.anevia.available'),
                                         ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                          'irabeth.trickster.friends', 'anevia_gone', 'ending.wound_closed',
                                          'engine.l12.commander_unreturned'),
                                         ()),
                                        (('irabeth.trickster.late_committed', 'ending.wound_closed',
                                          'crossroute.anevia.available'),
                                         ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                          'irabeth.trickster.friends', 'anevia_gone',
                                          'engine.l12.commander_unreturned'),
                                         ()),
                                        (('irabeth.trickster.pen_sent', 'crossroute.anevia.available'),
                                         ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                          'engine.l12.commander_unreturned'),
                                         ()),
                                        (('irabeth.trickster.pen_sent', 'ending.wound_closed',
                                          'crossroute.anevia.available'),
                                         ('irabeth.committed', 'irabeth.closed', 'engine.l12.commander_unreturned'),
                                         ())],
 ('irabeth.ending_changed', 'end'): [(('irabeth.trickster.late_committed',),
                                      ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                       'irabeth.trickster.friends', 'anevia_gone', 'ending.wound_closed',
                                       'engine.l12.commander_unreturned'),
                                      ()),
                                     (('irabeth.trickster.late_committed', 'anevia.trickster.returned'),
                                      ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                       'irabeth.trickster.friends', 'ending.wound_closed',
                                       'engine.l12.commander_unreturned'),
                                      ()),
                                     (('irabeth.trickster.late_committed', 'anevia.trickster.returned',
                                       'ending.wound_closed'),
                                      ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                       'irabeth.trickster.friends', 'engine.l12.commander_unreturned'),
                                      ()),
                                     (('irabeth.trickster.late_committed', 'ending.wound_closed'),
                                      ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                       'irabeth.trickster.friends', 'anevia_gone', 'engine.l12.commander_unreturned'),
                                      ()),
                                     (('irabeth.trickster.pen_sent', 'crossroute.anevia.available'),
                                      ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                       'engine.l12.commander_unreturned'),
                                      ()),
                                     (('irabeth.trickster.pen_sent', 'ending.wound_closed',
                                       'crossroute.anevia.available'),
                                      ('irabeth.committed', 'irabeth.closed', 'engine.l12.commander_unreturned'), ())],
 ('irabeth.ending_ascent', 'end'): [(('irabeth.trickster.late_committed', 'anevia.trickster.returned'),
                                     ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                      'irabeth.trickster.friends', 'ending.wound_closed',
                                      'engine.l12.commander_unreturned'),
                                     ()),
                                    (('irabeth.trickster.late_committed', 'anevia.trickster.returned',
                                      'ending.wound_closed'),
                                     ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                      'irabeth.trickster.friends', 'engine.l12.commander_unreturned'),
                                     ()),
                                    (('irabeth.trickster.late_committed', 'crossroute.anevia.available'),
                                     ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                      'irabeth.trickster.friends', 'anevia_gone', 'ending.wound_closed',
                                      'engine.l12.commander_unreturned'),
                                     ()),
                                    (('irabeth.trickster.late_committed', 'ending.wound_closed',
                                      'crossroute.anevia.available'),
                                     ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                      'irabeth.trickster.friends', 'anevia_gone', 'engine.l12.commander_unreturned'),
                                     ()),
                                    (('irabeth.trickster.pen_sent', 'crossroute.anevia.available'),
                                     ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                      'engine.l12.commander_unreturned'),
                                     ()),
                                    (('irabeth.trickster.pen_sent', 'ending.wound_closed',
                                      'crossroute.anevia.available'),
                                     ('irabeth.committed', 'irabeth.closed', 'engine.l12.commander_unreturned'), ())],
 ('irabeth.ending_sacrifice', 'end'): [(('irabeth.trickster.late_committed',),
                                        ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                         'irabeth.trickster.friends', 'anevia_gone', 'ending.wound_closed',
                                         'engine.l12.commander_unreturned'),
                                        ()),
                                       (('irabeth.trickster.late_committed', 'anevia.trickster.returned'),
                                        ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                         'irabeth.trickster.friends', 'ending.wound_closed',
                                         'engine.l12.commander_unreturned'),
                                        ()),
                                       (('irabeth.trickster.late_committed', 'anevia.trickster.returned',
                                         'ending.wound_closed'),
                                        ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                         'irabeth.trickster.friends', 'engine.l12.commander_unreturned'),
                                        ()),
                                       (('irabeth.trickster.late_committed', 'ending.wound_closed'),
                                        ('irabeth.committed', 'irabeth.closed', 'irabeth.trickster.declined',
                                         'irabeth.trickster.friends', 'anevia_gone',
                                         'engine.l12.commander_unreturned'),
                                        ()),
                                       (('irabeth.trickster.pen_sent',),
                                        ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                         'engine.l12.commander_unreturned'),
                                        ()),
                                       (('irabeth.trickster.pen_sent', 'ending.wound_closed'),
                                        ('irabeth.committed', 'irabeth.closed', 'engine.l12.commander_unreturned'),
                                        ())],
 ('irabeth.trickster.epilogue.under_orders', 'end'): [(('irabeth.trickster.late_committed',
                                                        'anevia.trickster.returned'),
                                                       ('irabeth.committed', 'irabeth.closed',
                                                        'irabeth.trickster.declined', 'irabeth.trickster.friends',
                                                        'ending.wound_closed', 'engine.l12.commander_unreturned'),
                                                       ()),
                                                      (('irabeth.trickster.late_committed', 'anevia.trickster.returned',
                                                        'ending.wound_closed'),
                                                       ('irabeth.committed', 'irabeth.closed',
                                                        'irabeth.trickster.declined', 'irabeth.trickster.friends',
                                                        'engine.l12.commander_unreturned'),
                                                       ()),
                                                      (('irabeth.trickster.late_committed',
                                                        'crossroute.anevia.available'),
                                                       ('irabeth.committed', 'irabeth.closed',
                                                        'irabeth.trickster.declined', 'irabeth.trickster.friends',
                                                        'anevia_gone', 'ending.wound_closed',
                                                        'engine.l12.commander_unreturned'),
                                                       ()),
                                                      (('irabeth.trickster.late_committed', 'ending.wound_closed',
                                                        'crossroute.anevia.available'),
                                                       ('irabeth.committed', 'irabeth.closed',
                                                        'irabeth.trickster.declined', 'irabeth.trickster.friends',
                                                        'anevia_gone', 'engine.l12.commander_unreturned'),
                                                       ()),
                                                      (('irabeth.trickster.pen_sent', 'crossroute.anevia.available'),
                                                       ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                                        'engine.l12.commander_unreturned'),
                                                       ()),
                                                      (('irabeth.trickster.pen_sent', 'ending.wound_closed',
                                                        'crossroute.anevia.available'),
                                                       ('irabeth.committed', 'irabeth.closed',
                                                        'engine.l12.commander_unreturned'),
                                                       ())],
 ('irabeth.trickster.epilogue.off_the_record', 'end'): [(('irabeth.trickster.late_committed',),
                                                         ('irabeth.committed', 'irabeth.closed',
                                                          'irabeth.trickster.declined', 'irabeth.trickster.friends',
                                                          'anevia_gone', 'ending.wound_closed',
                                                          'engine.l12.commander_unreturned'),
                                                         ()),
                                                        (('irabeth.trickster.late_committed',
                                                          'anevia.trickster.returned'),
                                                         ('irabeth.committed', 'irabeth.closed',
                                                          'irabeth.trickster.declined', 'irabeth.trickster.friends',
                                                          'ending.wound_closed', 'engine.l12.commander_unreturned'),
                                                         ()),
                                                        (('irabeth.trickster.late_committed',
                                                          'anevia.trickster.returned', 'ending.wound_closed'),
                                                         ('irabeth.committed', 'irabeth.closed',
                                                          'irabeth.trickster.declined', 'irabeth.trickster.friends',
                                                          'engine.l12.commander_unreturned'),
                                                         ()),
                                                        (('irabeth.trickster.late_committed', 'ending.wound_closed'),
                                                         ('irabeth.committed', 'irabeth.closed',
                                                          'irabeth.trickster.declined', 'irabeth.trickster.friends',
                                                          'anevia_gone', 'engine.l12.commander_unreturned'),
                                                         ()),
                                                        (('irabeth.trickster.pen_sent',),
                                                         ('irabeth.committed', 'irabeth.closed', 'ending.wound_closed',
                                                          'engine.l12.commander_unreturned'),
                                                         ()),
                                                        (('irabeth.trickster.pen_sent', 'ending.wound_closed'),
                                                         ('irabeth.committed', 'irabeth.closed',
                                                          'engine.l12.commander_unreturned'),
                                                         ())],
 ('anevia.trickster.epilogue.nailed_wardrobe', 'end'): [(('anevia.trickster.returned',
                                                          'anevia.irabeth_killed_by_commander'),
                                                         ('irabeth.trickster.returned',
                                                          'irabeth.trickster.cost.dug_out',
                                                          'irabeth.trickster.raised_on_record',
                                                          'engine.l12.commander_unreturned'),
                                                         (('anevia.trickster.terms_kept',
                                                           'anevia.trickster.cost.her_key'),)),
                                                        (('anevia.trickster.returned', 'anevia.trickster.declined'),
                                                         ('anevia.committed', 'anevia.closed',
                                                          'engine.l12.commander_unreturned'),
                                                         ()),
                                                        (('anevia.trickster.returned', 'anevia.trickster.friends'),
                                                         ('anevia.committed', 'anevia.closed',
                                                          'anevia.trickster.late_committed',
                                                          'engine.l12.commander_unreturned'),
                                                         ()),
                                                        (('anevia.trickster.returned',
                                                          'anevia.trickster.late_committed'),
                                                         ('anevia.committed', 'anevia.closed',
                                                          'anevia.trickster.declined', 'anevia.trickster.friends',
                                                          'engine.l12.commander_unreturned'),
                                                         ()),
                                                        (('anevia.trickster.returned',
                                                          'anevia.trickster.late_committed',
                                                          'irabeth.trickster.returned', 'irabeth.present_now',
                                                          'crossroute.irabeth.available'),
                                                         ('anevia.committed', 'anevia.closed',
                                                          'anevia.trickster.declined', 'anevia.trickster.friends',
                                                          'engine.l12.commander_unreturned'),
                                                         ()),
                                                        (('anevia.trickster.returned', 'anevia.trickster.terms_kept'),
                                                         ('engine.l12.commander_unreturned',), ()),
                                                        (('anevia.trickster.returned', 'irabeth_dead'),
                                                         ('irabeth.trickster.returned',
                                                          'anevia.irabeth_killed_by_commander',
                                                          'irabeth.trickster.cost.dug_out',
                                                          'irabeth.trickster.raised_on_record',
                                                          'engine.l12.commander_unreturned'),
                                                         (('anevia.trickster.terms_kept',
                                                           'anevia.trickster.cost.her_key'),))],
 ('anevia.trickster.epilogue.nailed_wardrobe_lover', 'end'): [(('anevia.trickster.returned',
                                                                'anevia.irabeth_killed_by_commander',
                                                                'anevia.outcome.route_open'),
                                                               ('irabeth.trickster.returned',
                                                                'irabeth.trickster.cost.dug_out',
                                                                'irabeth.trickster.raised_on_record',
                                                                'engine.l12.commander_unreturned'),
                                                               (('anevia.trickster.terms_kept',
                                                                 'anevia.trickster.cost.her_key'),)),
                                                              (('anevia.trickster.returned',
                                                                'anevia.trickster.declined'),
                                                               ('anevia.committed', 'anevia.closed',
                                                                'engine.l12.commander_unreturned'),
                                                               ()),
                                                              (('anevia.trickster.returned',
                                                                'anevia.trickster.friends'),
                                                               ('anevia.committed', 'anevia.closed',
                                                                'anevia.trickster.late_committed',
                                                                'engine.l12.commander_unreturned'),
                                                               ()),
                                                              (('anevia.trickster.returned',
                                                                'anevia.trickster.late_committed'),
                                                               ('anevia.committed', 'anevia.closed',
                                                                'anevia.trickster.declined', 'anevia.trickster.friends',
                                                                'engine.l12.commander_unreturned'),
                                                               ()),
                                                              (('anevia.trickster.returned',
                                                                'anevia.trickster.late_committed',
                                                                'irabeth.trickster.returned', 'irabeth.present_now'),
                                                               ('anevia.committed', 'anevia.closed',
                                                                'anevia.trickster.declined', 'anevia.trickster.friends',
                                                                'engine.l12.commander_unreturned'),
                                                               ()),
                                                              (('anevia.trickster.returned',
                                                                'anevia.trickster.terms_kept',
                                                                'anevia.outcome.route_open'),
                                                               ('engine.l12.commander_unreturned',), ()),
                                                              (('anevia.trickster.returned', 'irabeth_dead',
                                                                'anevia.outcome.route_open'),
                                                               ('irabeth.trickster.returned',
                                                                'anevia.irabeth_killed_by_commander',
                                                                'irabeth.trickster.cost.dug_out',
                                                                'irabeth.trickster.raised_on_record',
                                                                'engine.l12.commander_unreturned'),
                                                               (('anevia.trickster.terms_kept',
                                                                 'anevia.trickster.cost.her_key'),))],
 ('anevia.trickster.epilogue.nailed_wardrobe_closed', 'end'): [(('anevia.trickster.returned',
                                                                 'anevia.irabeth_killed_by_commander'),
                                                                ('irabeth.trickster.returned',
                                                                 'irabeth.trickster.cost.dug_out',
                                                                 'irabeth.trickster.raised_on_record',
                                                                 'engine.l12.commander_unreturned'),
                                                                (('anevia.trickster.terms_kept',
                                                                  'anevia.trickster.cost.her_key'),)),
                                                               (('anevia.trickster.returned',
                                                                 'anevia.trickster.declined'),
                                                                ('anevia.committed', 'anevia.closed',
                                                                 'engine.l12.commander_unreturned'),
                                                                ()),
                                                               (('anevia.trickster.returned',
                                                                 'anevia.trickster.friends'),
                                                                ('anevia.committed', 'anevia.closed',
                                                                 'anevia.trickster.late_committed',
                                                                 'engine.l12.commander_unreturned'),
                                                                ()),
                                                               (('anevia.trickster.returned',
                                                                 'anevia.trickster.late_committed'),
                                                                ('anevia.committed', 'anevia.closed',
                                                                 'anevia.trickster.declined',
                                                                 'anevia.trickster.friends',
                                                                 'engine.l12.commander_unreturned'),
                                                                ()),
                                                               (('anevia.trickster.returned',
                                                                 'anevia.trickster.late_committed',
                                                                 'irabeth.trickster.returned', 'irabeth.present_now'),
                                                                ('anevia.committed', 'anevia.closed',
                                                                 'anevia.trickster.declined',
                                                                 'anevia.trickster.friends',
                                                                 'engine.l12.commander_unreturned'),
                                                                ()),
                                                               (('anevia.trickster.returned',
                                                                 'anevia.trickster.terms_kept'),
                                                                ('engine.l12.commander_unreturned',), ()),
                                                               (('anevia.trickster.returned', 'irabeth_dead'),
                                                                ('irabeth.trickster.returned',
                                                                 'anevia.irabeth_killed_by_commander',
                                                                 'irabeth.trickster.cost.dug_out',
                                                                 'irabeth.trickster.raised_on_record',
                                                                 'engine.l12.commander_unreturned'),
                                                                (('anevia.trickster.terms_kept',
                                                                  'anevia.trickster.cost.her_key'),))],
 ('anevia.trickster.epilogue.nailed_wardrobe_widow', 'end'): [(('anevia.trickster.returned',
                                                                'anevia.irabeth_killed_by_commander'),
                                                               ('irabeth.trickster.returned',
                                                                'irabeth.trickster.cost.dug_out',
                                                                'irabeth.trickster.raised_on_record',
                                                                'engine.l12.commander_unreturned'),
                                                               (('anevia.trickster.terms_kept',
                                                                 'anevia.trickster.cost.her_key'),)),
                                                              (('anevia.trickster.returned',
                                                                'anevia.trickster.declined'),
                                                               ('anevia.committed', 'anevia.closed',
                                                                'engine.l12.commander_unreturned'),
                                                               ()),
                                                              (('anevia.trickster.returned',
                                                                'anevia.trickster.friends'),
                                                               ('anevia.committed', 'anevia.closed',
                                                                'anevia.trickster.late_committed',
                                                                'engine.l12.commander_unreturned'),
                                                               ()),
                                                              (('anevia.trickster.returned',
                                                                'anevia.trickster.late_committed'),
                                                               ('anevia.committed', 'anevia.closed',
                                                                'anevia.trickster.declined', 'anevia.trickster.friends',
                                                                'engine.l12.commander_unreturned'),
                                                               ()),
                                                              (('anevia.trickster.returned',
                                                                'anevia.trickster.late_committed',
                                                                'irabeth.trickster.returned', 'irabeth.present_now'),
                                                               ('anevia.committed', 'anevia.closed',
                                                                'anevia.trickster.declined', 'anevia.trickster.friends',
                                                                'engine.l12.commander_unreturned'),
                                                               ()),
                                                              (('anevia.trickster.returned',
                                                                'anevia.trickster.terms_kept'),
                                                               ('engine.l12.commander_unreturned',), ()),
                                                              (('anevia.trickster.returned', 'irabeth_dead'),
                                                               ('irabeth.trickster.returned',
                                                                'anevia.irabeth_killed_by_commander',
                                                                'irabeth.trickster.cost.dug_out',
                                                                'irabeth.trickster.raised_on_record',
                                                                'engine.l12.commander_unreturned'),
                                                               (('anevia.trickster.terms_kept',
                                                                 'anevia.trickster.cost.her_key'),))],
 ('anevia.trickster.epilogue.nailed_wardrobe_unforgiven', 'end'): [(('anevia.trickster.returned',
                                                                     'anevia.irabeth_killed_by_commander'),
                                                                    ('irabeth.trickster.returned',
                                                                     'irabeth.trickster.cost.dug_out',
                                                                     'irabeth.trickster.raised_on_record',
                                                                     'engine.l12.commander_unreturned'),
                                                                    (('anevia.trickster.terms_kept',
                                                                      'anevia.trickster.cost.her_key'),)),
                                                                   (('anevia.trickster.returned',
                                                                     'anevia.trickster.declined'),
                                                                    ('anevia.committed', 'anevia.closed',
                                                                     'engine.l12.commander_unreturned'),
                                                                    ()),
                                                                   (('anevia.trickster.returned',
                                                                     'anevia.trickster.friends'),
                                                                    ('anevia.committed', 'anevia.closed',
                                                                     'anevia.trickster.late_committed',
                                                                     'engine.l12.commander_unreturned'),
                                                                    ()),
                                                                   (('anevia.trickster.returned',
                                                                     'anevia.trickster.late_committed'),
                                                                    ('anevia.committed', 'anevia.closed',
                                                                     'anevia.trickster.declined',
                                                                     'anevia.trickster.friends',
                                                                     'engine.l12.commander_unreturned'),
                                                                    ()),
                                                                   (('anevia.trickster.returned',
                                                                     'anevia.trickster.late_committed',
                                                                     'irabeth.trickster.returned',
                                                                     'irabeth.present_now'),
                                                                    ('anevia.committed', 'anevia.closed',
                                                                     'anevia.trickster.declined',
                                                                     'anevia.trickster.friends',
                                                                     'engine.l12.commander_unreturned'),
                                                                    ()),
                                                                   (('anevia.trickster.returned',
                                                                     'anevia.trickster.terms_kept'),
                                                                    ('engine.l12.commander_unreturned',), ()),
                                                                   (('anevia.trickster.returned', 'irabeth_dead'),
                                                                    ('irabeth.trickster.returned',
                                                                     'anevia.irabeth_killed_by_commander',
                                                                     'irabeth.trickster.cost.dug_out',
                                                                     'irabeth.trickster.raised_on_record',
                                                                     'engine.l12.commander_unreturned'),
                                                                    (('anevia.trickster.terms_kept',
                                                                      'anevia.trickster.cost.her_key'),))]}


class Lane12Tests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with patch.object(lane, "integrate"), patch.object(engine_eng3_ab, "integrate"):
            cls.before = make_expansion()
        cls.after = copy.deepcopy(cls.before)
        lane.integrate(cls.after)
        cls.final = fresh_story()

    def test_saved_scene_node_relationship_and_choice_positions(self):
        self.assertEqual(list(self.before["Relationships"]), list(self.after["Relationships"]))
        self.assertEqual([s["Id"] for s in self.before["Scenes"]], [s["Id"] for s in self.after["Scenes"]])
        for old, new in zip(self.before["Scenes"], self.after["Scenes"]):
            self.assertEqual([n["Id"] for n in old["Nodes"]], [n["Id"] for n in new["Nodes"]])
            for a, b in zip(old["Nodes"], new["Nodes"]):
                self.assertEqual(without_prose(a["Choices"]), without_prose(b["Choices"]), old["Id"] + "/" + a["Id"])

    def test_areelu_uncollected_world_variants_follow_flags(self):
        scene = next(s for s in self.after['Scenes'] if s['Id'] == 'areelu.trickster.finale.unnamed')
        node = next(n for n in scene['Nodes'] if n['Id'] == 'end')
        observed = {gate_key(p) for p in node['Paragraphs']}
        groups = (('areelu.sacrifice_wound', 'areelu.sacrifice_before'),)
        self.assertIn((('ending.wound_closed',), (), groups), observed)
        self.assertIn(((), ('ending.wound_closed',), groups), observed)
        self.assertIn((('areelu.trickster.term.life',), (), ()), observed)

    def test_world_fact_and_bereavement_predicates_read_native_state(self):
        self.assertEqual(self.after["Derived"][lane.DEAD], [["sacrifice"]])
        self.assertEqual(self.after["DerivedForbids"][lane.DEAD], ["trickster.commander_back"])
        self.assertEqual(self.after["Derived"]["engine.l12.crossroads"],
                         [["ending.trickster_allplanes"], ["ending.trickster_allplanes_fw"]])
        self.assertEqual(self.after["SeenCues"]["engine.l12.kenabres_rebuilding"],
                         ["fc65929e0c9e4a9fa03309418c2d29bb"])

    def test_commander_mourning_mutation_is_rejected(self):
        story = copy.deepcopy(self.final)
        page = next(s for s in story["Scenes"] if s["Id"] == "anevia.ending_sacrifice")
        p = next(n for n in page["Nodes"] if n["Id"] == "end")["Paragraphs"][7]
        p["Forbids"].remove(lane.DEAD)
        self.assertTrue(any(f["scene"] == page["Id"] for f in findings(commander_alive, story)))
        self.assertTrue(any("living continuation" in error for error in earned_presence_lint.check(story)[0]))

    def test_world_fact_guard_removal_is_rejected(self):
        story = copy.deepcopy(self.final)
        page = next(s for s in story["Scenes"] if s["Id"] == "chadali.trickster.epilogue.lucky_night")
        p = next(n for n in page["Nodes"] if n["Id"] == "page")["Paragraphs"][15]
        p["Requires"].remove("ending.wound_closed")
        self.assertTrue(any(f["scene"] == page["Id"] for f in findings(world_facts, story)))

    def test_all_bereavement_siblings_are_disjoint(self):
        scenes = {s['Id']: s for s in self.final['Scenes']}
        self.assertTrue({'anevia', 'irabeth'} <= {sid.split('.')[0] for sid, _ in LIVING_SURFACES})
        for (scene_id, node_id), signatures in LIVING_SURFACES.items():
            node = next(n for n in scenes[scene_id]['Nodes'] if n['Id'] == node_id)
            observed = {gate_key(p) for p in node['Paragraphs']}
            self.assertTrue(set(signatures) <= observed, (scene_id, node_id))
            self.assertTrue(all(lane.DEAD in forbids for _, forbids, _ in signatures))

    def test_off_island_and_physical_contracts_include_manual_reads(self):
        scenes = {s["Id"]: s for s in self.after["Scenes"]}
        for contract in lane.inventory("location_inventory_contracts.json")["venues"]:
            self.assertEqual(scenes[contract["scene"]]["Areas"], contract["areas"])
        self.assertNotIn("c876d5303f4a19f4a80b0cc9b313db6f", scenes["melazmera.trickster.ch4.hunt_found"]["Areas"])

    def test_existing_finale_variants_are_preserved_without_contradictory_appendices(self):
        old = next(s for s in self.before["Scenes"] if s["Id"] == "melazmera.trickster.epilogue.left_free")
        new = next(s for s in self.after["Scenes"] if s["Id"] == old["Id"])
        self.assertEqual(without_prose(old["Nodes"][0]["Paragraphs"]), without_prose(new["Nodes"][0]["Paragraphs"]))
        for a, b in zip(self.before["Scenes"], self.after["Scenes"]):
            for original, changed in zip(a["Nodes"], b["Nodes"]):
                for paragraph in changed.get("Paragraphs", [])[len(original.get("Paragraphs", [])):]:
                    self.assertFalse(set(paragraph.get("Requires", [])) & set(paragraph.get("Forbids", [])), a["Id"])

    def test_lint_does_not_excuse_same_block_unrelated_staging(self):
        story = copy.deepcopy(self.final)
        scene = next(s for s in story["Scenes"] if s["Id"] == "galfrey.trickster.ch4.letter")
        scene["Nodes"][0]["Text"] += " {n}You stand in Drezen's citadel.{/n}"
        self.assertTrue(any(f["scene"] == scene["Id"] for f in findings(location_staging, story)))

    def test_rewritten_behavior_rejects_mutated_fixture(self):
        scene = next(s for s in self.final['Scenes'] if s['Id'] == 'anevia.ending_sacrifice')
        paragraph = next(p for n in scene['Nodes'] if n['Id'] == 'end' for p in n['Paragraphs']
                         if p['Requires'] == ['anevia.trickster.returned', 'anevia.trickster.late_committed'])
        with patch.dict(paragraph, Forbids=[f for f in paragraph['Forbids'] if f != lane.DEAD]):
            with patch.object(self, "_outcome", None), self.assertRaises(AssertionError):
                self.test_all_bereavement_siblings_are_disjoint()


if __name__ == "__main__":
    unittest.main()
