"""Frozen integration save references for the two changed Soana modules."""
import unittest
from storylines import soana_late_campaign, soana_trickster

BASELINE = {'soana_late_campaign': {'soana.past_the_firelight': {'start': [('heard', (), None, None),
                                                                ('told', (), None, None)],
                                                      'heard': [('silent', (), None, None),
                                                                ('tested', (), None, None),
                                                                ('followed', (), None, None)],
                                                      'told': [('silent', (), None, None),
                                                               ('tested', (), None, None),
                                                               ('followed', (), None, None)],
                                                      'silent': [(None,
                                                                  ('soana.abyss_voice_unanswered',),
                                                                  None,
                                                                  None)],
                                                      'tested': [(None,
                                                                  ('soana.abyss_voice_tested',),
                                                                  None,
                                                                  None)],
                                                      'followed': [(None,
                                                                    ('soana.abyss_voice_followed',),
                                                                    None,
                                                                    None)]},
                         'soana.when_the_road_returns': {'start': [('welcome', (), None, None),
                                                                   ('friend', (), None, None),
                                                                   (None, (), None, None)],
                                                         'welcome': [('nursery', (), None, None),
                                                                     ('voice_silent', (), None, None),
                                                                     ('voice_tested', (), None, None),
                                                                     ('voice_followed', (), None, None)],
                                                         'friend': [('nursery', (), None, None),
                                                                    ('voice_silent', (), None, None),
                                                                    ('voice_tested', (), None, None),
                                                                    ('voice_followed', (), None, None)],
                                                         'nursery': [('saved', (), None, None),
                                                                     ('lost', (), None, None)],
                                                         'saved': [('path', (), None, None)],
                                                         'lost': [('path', (), None, None)],
                                                         'path': [('cleft', (), None, None),
                                                                  ('flood', (), None, None)],
                                                         'cleft': [('end', (), None, None)],
                                                         'flood': [('end', (), None, None)],
                                                         'end': [(None, ('soana.late_returned',), None, None)],
                                                         'voice_silent': [('nursery', (), None, None)],
                                                         'voice_tested': [('nursery', (), None, None)],
                                                         'voice_followed': [('nursery', (), None, None)]},
                         'soana.a_track_with_two_ends': {'start': [(None,
                                                                    (),
                                                                    None,
                                                                    {'Skill': 'SkillLoreNature',
                                                                     'DC': 26,
                                                                     'Success': 'read',
                                                                     'Failure': 'mistake',
                                                                     'CommanderOnly': True}),
                                                                   ('slow', (), None, None),
                                                                   (None, (), None, None)],
                                                         'read': [('found_end', (), None, None)],
                                                         'found_end': [(None,
                                                                        ('soana.late_track_read',
                                                                         'soana.late_trail_known'),
                                                                        None,
                                                                        None)],
                                                         'mistake': [('late_end', (), None, None)],
                                                         'slow': [('slow_end', (), None, None)],
                                                         'late_end': [(None,
                                                                       ('soana.late_track_missed',
                                                                        'soana.late_trail_known'),
                                                                       None,
                                                                       None)],
                                                         'slow_end': [(None,
                                                                       ('soana.late_track_slow',
                                                                        'soana.late_trail_known'),
                                                                       None,
                                                                       None)]},
                         'soana.what_the_hollow_costs': {'start': [('stores', (), None, None),
                                                                   (None, (), None, None)],
                                                         'stores': [('ground', (), None, None)],
                                                         'ground': [('thorn', (), None, None)],
                                                         'thorn': [('reserve', (), None, None),
                                                                   ('harvest', (), None, None)],
                                                         'reserve': [(None,
                                                                      ('soana.late_reserve',
                                                                       'soana.late_boundary_agreed'),
                                                                      None,
                                                                      None)],
                                                         'harvest': [(None,
                                                                      ('soana.late_harvest',
                                                                       'soana.late_boundary_agreed'),
                                                                      None,
                                                                      None)]},
                         'soana.where_the_steps_end': {'start': [('changed_role', (), None, None),
                                                                 ('role', (), None, None),
                                                                 (None, (), None, None)],
                                                       'changed_role': [('placing', (), None, None)],
                                                       'role': [('placing', (), None, None)],
                                                       'placing': [('strong', (), None, None),
                                                                   ('soft', (), None, None)],
                                                       'strong': [('strong_end', (), None, None)],
                                                       'soft': [('soft_end', (), None, None)],
                                                       'strong_end': [(None,
                                                                       ('soana.late_thorn_strong',
                                                                        'soana.late_thorn_tested'),
                                                                       None,
                                                                       None)],
                                                       'soft_end': [(None,
                                                                     ('soana.late_thorn_soft',
                                                                      'soana.late_thorn_tested'),
                                                                     None,
                                                                     None)]},
                         'soana.the_days_she_counted': {'start': [('reserve', (), None, None),
                                                                  ('harvest', (), None, None),
                                                                  (None, (), None, None)],
                                                        'reserve': [('meret', (), None, None)],
                                                        'harvest': [('meret', (), None, None)],
                                                        'meret': [('guardian', (), None, None)],
                                                        'guardian': [('bound', (), None, None),
                                                                     ('dead', (), None, None),
                                                                     ('dead', (), None, None)],
                                                        'bound': [('letter', (), None, None)],
                                                        'dead': [('letter', (), None, None)],
                                                        'letter': [('future', (), None, None),
                                                                   ('friend', (), None, None)],
                                                        'future': [('commit', (), None, None),
                                                                   ('open', (), None, None),
                                                                   ('part_as_friends', (), None, None)],
                                                        'commit': [(None,
                                                                    ('soana.committed',
                                                                     'soana.late_future_chosen'),
                                                                    None,
                                                                    None)],
                                                        'open': [(None,
                                                                  ('soana.late_open', 'soana.late_future_chosen'),
                                                                  None,
                                                                  None)],
                                                        'part_as_friends': [(None,
                                                                             ('soana.late_friends',
                                                                              'soana.late_romance_ended',
                                                                              'soana.late_future_chosen'),
                                                                             None,
                                                                             None)],
                                                        'friend': [(None,
                                                                    ('soana.late_friends',
                                                                     'soana.late_future_chosen'),
                                                                    None,
                                                                    None)]},
                         'soana.before_the_far_road': {'start': [('beloved', (), None, None),
                                                                 ('courtship', (), None, None),
                                                                 ('friend', (), None, None),
                                                                 (None, (), None, None)],
                                                       'beloved': [('desire', (), None, None)],
                                                       'courtship': [('desire', (), None, None)],
                                                       'desire': [('night', (), None, None),
                                                                  ('kiss', (), None, None),
                                                                  ('hold', (), None, None)],
                                                       'night': [('leave_night', (), None, None)],
                                                       'leave_night': [(None,
                                                                        ('soana.lovers',
                                                                         'soana.late_farewell_night',
                                                                         'soana.late_campaign_kept'),
                                                                        None,
                                                                        None)],
                                                       'kiss': [(None,
                                                                 ('soana.late_farewell_kiss',
                                                                  'soana.late_campaign_kept'),
                                                                 None,
                                                                 None)],
                                                       'hold': [(None,
                                                                 ('soana.late_farewell_held',
                                                                  'soana.late_campaign_kept'),
                                                                 None,
                                                                 None)],
                                                       'friend': [(None,
                                                                   ('soana.late_farewell_friend',
                                                                    'soana.late_campaign_kept'),
                                                                   None,
                                                                   None)]},
                         'soana.ending_kept_life': {'start': [(None, (), None, None)]},
                         'soana.ending_chosen_visits': {'start': [(None, (), None, None)]},
                         'soana.ending_familiar_company': {'start': [(None, (), None, None)]},
                         'soana.ending_sacrifice': {'start': [(None, (), None, None)]},
                         'soana.ending_beyond_the_forest': {'start': [(None, (), None, None)]},
                         'soana.ending_unrecognizable_return': {'start': [(None, (), None, None)]},
                         'soana.ending_native_loss': {'start': [('camellia', (), None, None),
                                                                ('dead', (), None, None),
                                                                ('forest', (), None, None)],
                                                      'camellia': [(None, (), None, None)],
                                                      'dead': [(None, (), None, None)],
                                                      'forest': [(None, (), None, None)]},
                         'soana.ending_aeon': {'start': [(None, (), None, None)]},
                         'soana.ending_unfinished_sacrifice': {'start': [(None, (), None, None)]},
                         'soana.ending_unfinished_ascent': {'start': [(None, (), None, None)]},
                         'soana.ending_unfinished_change': {'start': [(None, (), None, None)]},
                         'soana.ending_unfinished_loss': {'start': [('camellia', (), None, None),
                                                                    ('dead', (), None, None),
                                                                    ('forest', (), None, None)],
                                                          'camellia': [(None, (), None, None)],
                                                          'dead': [(None, (), None, None)],
                                                          'forest': [(None, (), None, None)]}},
 'soana_trickster': {'soana.trickster.handover.after_quest': {'start': [('cost', (), None, None)],
                                                              'cost': [(None,
                                                                        ('soana.trickster.primed',
                                                                         'soana.trickster.cost.blood_given'),
                                                                        'fef727987297e8d4eb34068688fdac27',
                                                                        None)]},
                     'soana.trickster.handover.after_bear_a': {'start': [('camellia', (), None, None)],
                                                               'camellia': [(None,
                                                                             ('soana.trickster.primed',
                                                                              'soana.trickster.cost.blood_given'),
                                                                             'c6b676fa989a5494cb6ce0c981979907',
                                                                             None)]},
                     'soana.trickster.handover.after_bear_b': {'start': [('camellia', (), None, None)],
                                                               'camellia': [(None,
                                                                             ('soana.trickster.primed',
                                                                              'soana.trickster.cost.blood_given'),
                                                                             '74664ddd7bb36744ba825c29aad6f4b3',
                                                                             None)]},
                     'soana.trickster.killed.knot': {'start': [('orso', (), None, None),
                                                               ('spirit', (), None, None)],
                                                     'orso': [('read', (), None, None), ('marks', (), None, None)],
                                                     'spirit': [('read', (), None, None),
                                                                ('marks', (), None, None),
                                                                ('carcass', (), None, None),
                                                                ('pelt', (), None, None)],
                                                     'read': [('wake_clay',
                                                               ('soana.trickster.returned',
                                                                'soana.started',
                                                                'soana.trickster.cost.guardian_paid',
                                                                'soana.trickster.cost.medallion_spent',
                                                                'soana.trickster.cost.leash_held'),
                                                               None,
                                                               None),
                                                              ('wake_brand',
                                                               ('soana.trickster.returned',
                                                                'soana.started',
                                                                'soana.trickster.cost.guardian_paid',
                                                                'soana.trickster.cost.leash_held'),
                                                               None,
                                                               None),
                                                              (None,
                                                               ('soana.closed', 'soana.trickster.refused'),
                                                               None,
                                                               None)],
                                                     'marks': [('wake_clay',
                                                                ('soana.trickster.returned',
                                                                 'soana.started',
                                                                 'soana.trickster.cost.guardian_paid',
                                                                 'soana.trickster.cost.medallion_spent',
                                                                 'soana.trickster.cost.leash_held'),
                                                                None,
                                                                None),
                                                               ('wake_brand',
                                                                ('soana.trickster.returned',
                                                                 'soana.started',
                                                                 'soana.trickster.cost.guardian_paid',
                                                                 'soana.trickster.cost.leash_held'),
                                                                None,
                                                                None),
                                                               (None,
                                                                ('soana.closed', 'soana.trickster.refused'),
                                                                None,
                                                                None)],
                                                     'carcass': [('bait',
                                                                  ('soana.trickster.cost.knot_recut',),
                                                                  None,
                                                                  None),
                                                                 (None,
                                                                  ('soana.closed', 'soana.trickster.refused'),
                                                                  None,
                                                                  None)],
                                                     'pelt': [('bait',
                                                               ('soana.trickster.cost.knot_recut',),
                                                               None,
                                                               None),
                                                              (None,
                                                               ('soana.closed', 'soana.trickster.refused'),
                                                               None,
                                                               None)],
                                                     'bait': [('wake_clay',
                                                               ('soana.trickster.returned',
                                                                'soana.started',
                                                                'soana.trickster.cost.guardian_paid',
                                                                'soana.trickster.cost.medallion_spent',
                                                                'soana.trickster.cost.leash_held'),
                                                               None,
                                                               None),
                                                              ('wake_brand',
                                                               ('soana.trickster.returned',
                                                                'soana.started',
                                                                'soana.trickster.cost.guardian_paid',
                                                                'soana.trickster.cost.leash_held'),
                                                               None,
                                                               None),
                                                              (None,
                                                               ('soana.closed', 'soana.trickster.refused'),
                                                               None,
                                                               None)],
                                                     'wake_clay': [('wake_orso', (), None, None),
                                                                   ('wake_spirit', (), None, None)],
                                                     'wake_brand': [('wake_orso', (), None, None),
                                                                    ('wake_spirit', (), None, None)],
                                                     'wake_orso': [('soana', (), None, None)],
                                                     'wake_spirit': [('soana', (), None, None)],
                                                     'soana': [(None, (), None, None)]},
                     'soana.trickster.returned.graveyard': {'start': [('orso', (), None, None),
                                                                      ('spirit', (), None, None)],
                                                            'orso': [('dig', (), None, None)],
                                                            'spirit': [('dig', (), None, None)],
                                                            'dig': [('dug',
                                                                     ('soana.trickster.graveyard_kept',
                                                                      'soana.trickster.cost.grave_dug'),
                                                                     None,
                                                                     None),
                                                                    ('bought',
                                                                     ('soana.trickster.graveyard_kept',
                                                                      'soana.trickster.cost.grave_bought'),
                                                                     None,
                                                                     None),
                                                                    (None,
                                                                     ('soana.closed',
                                                                      'soana.trickster.refused',
                                                                      'soana.trickster.cost.left_the_grave'),
                                                                     None,
                                                                     None)],
                                                            'dug': [('decide', (), None, None)],
                                                            'bought': [('decide', (), None, None)],
                                                            'decide': [(None, (), None, None),
                                                                       (None,
                                                                        ('soana.closed',
                                                                         'soana.trickster.refused'),
                                                                        None,
                                                                        None)]},
                     'soana.trickster.returned.terms': {'start': [('dug', (), None, None),
                                                                  ('bought', (), None, None),
                                                                  ('price', (), None, None),
                                                                  ('price_clay', (), None, None)],
                                                        'dug': [('price', (), None, None),
                                                                ('price_clay', (), None, None)],
                                                        'bought': [('price', (), None, None),
                                                                   ('price_clay', (), None, None)],
                                                        'price': [('bind', (), None, None),
                                                                  ('no', (), None, None),
                                                                  ('fool', (), None, None),
                                                                  ('friend',
                                                                   ('soana.trickster.friends',),
                                                                   None,
                                                                   None)],
                                                        'bind': [('night',
                                                                  ('soana.committed',
                                                                   'soana.trickster.cost.knot_bearer'),
                                                                  None,
                                                                  None),
                                                                 ('no', (), None, None)],
                                                        'no': [(None, ('soana.trickster.declined',), None, None)],
                                                        'fool': [(None,
                                                                  ('soana.closed', 'soana.trickster.refused'),
                                                                  None,
                                                                  None)],
                                                        'night': [('morning', (), None, None)],
                                                        'morning': [(None, (), None, None)],
                                                        'friend': [(None,
                                                                    ('soana.trickster.cost.leash_reclaimed',),
                                                                    None,
                                                                    None)],
                                                        'price_clay': [('bind_clay', (), None, None),
                                                                       ('no', (), None, None),
                                                                       ('fool', (), None, None),
                                                                       ('friend',
                                                                        ('soana.trickster.friends',),
                                                                        None,
                                                                        None)],
                                                        'bind_clay': [('night_clay',
                                                                       ('soana.committed',
                                                                        'soana.trickster.cost.knot_bearer'),
                                                                       None,
                                                                       None),
                                                                      ('no', (), None, None)],
                                                        'night_clay': [('morning', (), None, None)]},
                     'soana.trickster.returned.second_ask': {'start': [('price', (), None, None)],
                                                             'price': [('cut',
                                                                        ('soana.committed',
                                                                         'soana.trickster.cost.knot_bearer',
                                                                         'soana.trickster.cost.second_ask'),
                                                                        None,
                                                                        None),
                                                                       (None,
                                                                        ('soana.closed',
                                                                         'soana.trickster.refused'),
                                                                        None,
                                                                        None),
                                                                       ('cut',
                                                                        ('soana.committed',
                                                                         'soana.trickster.cost.knot_bearer',
                                                                         'soana.trickster.cost.second_ask'),
                                                                        None,
                                                                        None)],
                                                             'night': [('morning', (), None, None)],
                                                             'morning': [(None, (), None, None)],
                                                             'night_clay': [('morning', (), None, None)],
                                                             'cut': [('night', (), None, None),
                                                                     ('night_clay', (), None, None)]},
                     'soana.trickster.returned.rebind': {'start': [('camellia', (), None, None),
                                                                   ('own', (), None, None),
                                                                   ('unknown', (), None, None)],
                                                         'camellia': [('price', (), None, None)],
                                                         'own': [('price', (), None, None)],
                                                         'price': [('night',
                                                                    ('soana.trickster.cost.knot_bearer',
                                                                     'soana.trickster.rebind'),
                                                                    None,
                                                                    None),
                                                                   ('refuse',
                                                                    ('soana.trickster.rebind_declined',),
                                                                    None,
                                                                    None),
                                                                   ('night_clay',
                                                                    ('soana.trickster.cost.knot_bearer',
                                                                     'soana.trickster.rebind'),
                                                                    None,
                                                                    None)],
                                                         'refuse': [(None,
                                                                     ('soana.trickster.cost.leash_reclaimed',),
                                                                     None,
                                                                     None)],
                                                         'night': [('morning', (), None, None)],
                                                         'morning': [(None, (), None, None)],
                                                         'night_clay': [('morning', (), None, None)],
                                                         'unknown': [('price', (), None, None)]},
                     'soana.trickster.returned.accounting': {'start': [('camellia', (), None, None),
                                                                       ('own', (), None, None),
                                                                       ('unknown', (), None, None),
                                                                       ('camellia_lover', (), None, None),
                                                                       ('own_lover', (), None, None)],
                                                             'camellia': [('answered',
                                                                           ('soana.trickster.accounting_answered',),
                                                                           None,
                                                                           None),
                                                                          ('evasive', (), None, None),
                                                                          ('dismiss',
                                                                           ('soana.closed',
                                                                            'soana.trickster.refused',
                                                                            'soana.trickster.accounting_refused'),
                                                                           None,
                                                                           None)],
                                                             'own': [('answered',
                                                                      ('soana.trickster.accounting_answered',),
                                                                      None,
                                                                      None),
                                                                     ('evasive', (), None, None),
                                                                     ('dismiss',
                                                                      ('soana.closed',
                                                                       'soana.trickster.refused',
                                                                       'soana.trickster.accounting_refused'),
                                                                      None,
                                                                      None)],
                                                             'unknown': [('answered',
                                                                          ('soana.trickster.accounting_answered',),
                                                                          None,
                                                                          None),
                                                                         ('evasive', (), None, None),
                                                                         ('dismiss',
                                                                          ('soana.closed',
                                                                           'soana.trickster.refused',
                                                                           'soana.trickster.accounting_refused'),
                                                                          None,
                                                                          None)],
                                                             'camellia_lover': [('answered',
                                                                                 ('soana.trickster.accounting_answered',),
                                                                                 None,
                                                                                 None),
                                                                                ('evasive', (), None, None),
                                                                                ('dismiss',
                                                                                 ('soana.closed',
                                                                                  'soana.trickster.refused',
                                                                                  'soana.trickster.accounting_refused'),
                                                                                 None,
                                                                                 None)],
                                                             'own_lover': [('answered',
                                                                            ('soana.trickster.accounting_answered',),
                                                                            None,
                                                                            None),
                                                                           ('evasive', (), None, None),
                                                                           ('dismiss',
                                                                            ('soana.closed',
                                                                             'soana.trickster.refused',
                                                                             'soana.trickster.accounting_refused'),
                                                                            None,
                                                                            None)],
                                                             'evasive': [('repeat', (), None, None),
                                                                         ('dismiss',
                                                                          ('soana.closed',
                                                                           'soana.trickster.refused',
                                                                           'soana.trickster.accounting_refused'),
                                                                          None,
                                                                          None)],
                                                             'repeat': [('answered',
                                                                         ('soana.trickster.accounting_answered',),
                                                                         None,
                                                                         None),
                                                                        ('answered',
                                                                         ('soana.trickster.accounting_answered',),
                                                                         None,
                                                                         None),
                                                                        ('answered',
                                                                         ('soana.trickster.accounting_answered',),
                                                                         None,
                                                                         None),
                                                                        ('answered',
                                                                         ('soana.trickster.accounting_answered',),
                                                                         None,
                                                                         None),
                                                                        ('answered',
                                                                         ('soana.trickster.accounting_answered',),
                                                                         None,
                                                                         None),
                                                                        ('dismiss',
                                                                         ('soana.closed',
                                                                          'soana.trickster.refused',
                                                                          'soana.trickster.accounting_refused'),
                                                                         None,
                                                                         None)],
                                                             'answered': [('down', (), None, None),
                                                                          ('down_friend', (), None, None),
                                                                          ('dismiss',
                                                                           ('soana.closed',
                                                                            'soana.trickster.refused',
                                                                            'soana.trickster.accounting_refused'),
                                                                           None,
                                                                           None)],
                                                             'down': [('diggers', (), None, None),
                                                                      ('work', (), None, None)],
                                                             'down_friend': [('diggers_friend', (), None, None),
                                                                             ('work_friend', (), None, None)],
                                                             'diggers': [('work', (), None, None)],
                                                             'diggers_friend': [('work_friend', (), None, None)],
                                                             'work': [('judged',
                                                                       ('soana.trickster.cost.stream_cleared',
                                                                        'soana.trickster.cost.nursery_guarded'),
                                                                       None,
                                                                       None)],
                                                             'work_friend': [('friend',
                                                                              ('soana.trickster.cost.stream_cleared',
                                                                               'soana.trickster.cost.nursery_guarded'),
                                                                              None,
                                                                              None)],
                                                             'judged': [(None,
                                                                         ('soana.trickster.accounting_invited',),
                                                                         None,
                                                                         None),
                                                                        ('friend', (), None, None),
                                                                        ('dismiss',
                                                                         ('soana.closed',
                                                                          'soana.trickster.refused',
                                                                          'soana.trickster.accounting_refused'),
                                                                         None,
                                                                         None)],
                                                             'friend': [(None,
                                                                         ('soana.trickster.friends',
                                                                          'soana.trickster.accounting_friend',
                                                                          'soana.trickster.cost.leash_reclaimed'),
                                                                         None,
                                                                         None)],
                                                             'dismiss': [(None, (), None, None)]},
                     'soana.trickster.handover.winter_portion': {'start': [('shared',
                                                                            ('soana.trickster.cost.portion_shared',),
                                                                            None,
                                                                            None),
                                                                           ('watched',
                                                                            ('soana.trickster.portion_watched',),
                                                                            None,
                                                                            None)],
                                                                 'shared': [(None, (), None, None)],
                                                                 'watched': [(None, (), None, None)]},
                     'soana.trickster.missed.dice_bowl': {'start': [(None,
                                                                     ('soana.trickster.primed_dice',),
                                                                     None,
                                                                     None)]},
                     'soana.trickster.missed.crooked_luck': {'start': [('price', (), None, None)],
                                                             'price': [(None,
                                                                        ('soana.trickster.luck_kept',
                                                                         'soana.trickster.cost.catchup',
                                                                         'soana.started',
                                                                         'soana.trickster.cost.luck_fed'),
                                                                        None,
                                                                        None),
                                                                       (None,
                                                                        ('soana.trickster.luck_refused',),
                                                                        None,
                                                                        None)]},
                     'soana.trickster.missed.late_luck': {'start': [('price', (), None, None)],
                                                          'price': [(None,
                                                                     ('soana.trickster.primed_dice',
                                                                      'soana.trickster.cost.late',
                                                                      'soana.trickster.luck_kept',
                                                                      'soana.trickster.cost.catchup',
                                                                      'soana.started',
                                                                      'soana.trickster.cost.luck_fed'),
                                                                     None,
                                                                     None),
                                                                    ('refused',
                                                                     ('soana.trickster.luck_refused',
                                                                      'soana.trickster.cost.late'),
                                                                     None,
                                                                     None)],
                                                          'refused': [(None, (), None, None)]},
                     'soana.trickster.missed.she_bear': {'start': [('question', (), None, None)],
                                                         'question': [('rest',
                                                                       ('soana.trickster.luck_tested',
                                                                        'soana.trickster.answered_rest'),
                                                                       None,
                                                                       None),
                                                                      ('roll',
                                                                       ('soana.trickster.luck_tested',
                                                                        'soana.trickster.answered_roll'),
                                                                       None,
                                                                       None),
                                                                      ('cheat',
                                                                       ('soana.trickster.luck_tested',
                                                                        'soana.trickster.answered_cheat'),
                                                                       None,
                                                                       None),
                                                                      ('why', (), None, None),
                                                                      ('rest_plain',
                                                                       ('soana.trickster.luck_tested',
                                                                        'soana.trickster.answered_rest'),
                                                                       None,
                                                                       None),
                                                                      ('roll_plain',
                                                                       ('soana.trickster.luck_tested',
                                                                        'soana.trickster.answered_roll'),
                                                                       None,
                                                                       None)],
                                                         'why': [('rest',
                                                                  ('soana.trickster.luck_tested',
                                                                   'soana.trickster.answered_rest'),
                                                                  None,
                                                                  None),
                                                                 ('roll',
                                                                  ('soana.trickster.luck_tested',
                                                                   'soana.trickster.answered_roll'),
                                                                  None,
                                                                  None),
                                                                 ('cheat',
                                                                  ('soana.trickster.luck_tested',
                                                                   'soana.trickster.answered_cheat'),
                                                                  None,
                                                                  None),
                                                                 ('rest_plain',
                                                                  ('soana.trickster.luck_tested',
                                                                   'soana.trickster.answered_rest'),
                                                                  None,
                                                                  None),
                                                                 ('roll_plain',
                                                                  ('soana.trickster.luck_tested',
                                                                   'soana.trickster.answered_roll'),
                                                                  None,
                                                                  None)],
                                                         'rest': [(None, (), None, None)],
                                                         'rest_plain': [(None, (), None, None)],
                                                         'roll': [(None, (), None, None)],
                                                         'roll_plain': [(None, (), None, None)],
                                                         'cheat': [(None, (), None, None)]},
                     'soana.trickster.missed.bowl': {'start': [('rest', (), None, None),
                                                               ('roll', (), None, None),
                                                               ('cheat', (), None, None),
                                                               ('terms', (), None, None)],
                                                     'rest': [('terms', (), None, None)],
                                                     'roll': [('terms', (), None, None)],
                                                     'cheat': [('terms', (), None, None)],
                                                     'terms': [('night',
                                                                ('soana.committed',
                                                                 'soana.trickster.cost.die_in_her_bowl'),
                                                                None,
                                                                None),
                                                               ('no', (), None, None),
                                                               ('taken', (), None, None),
                                                               ('friend',
                                                                ('soana.trickster.friends',),
                                                                None,
                                                                None)],
                                                     'friend': [(None, (), None, None)],
                                                     'no': [(None, ('soana.trickster.declined',), None, None)],
                                                     'taken': [(None,
                                                                ('soana.closed', 'soana.trickster.refused'),
                                                                None,
                                                                None)],
                                                     'night': [('threshold', (), None, None)],
                                                     'threshold': [('morning', (), None, None)],
                                                     'morning': [(None, (), None, None)]},
                     'soana.trickster.missed.second_ask': {'start': [('night',
                                                                      ('soana.committed',
                                                                       'soana.trickster.cost.die_in_her_bowl',
                                                                       'soana.trickster.cost.pair_given'),
                                                                      None,
                                                                      None),
                                                                     (None,
                                                                      ('soana.closed', 'soana.trickster.refused'),
                                                                      None,
                                                                      None)],
                                                           'night': [('threshold', (), None, None)],
                                                           'threshold': [('morning', (), None, None)],
                                                           'morning': [(None, (), None, None)]},
                     'soana.trickster.epilogue.knot': {'start': [(None, (), None, None)]},
                     'soana.trickster.epilogue.luck': {'start': [(None, (), None, None)]},
                     'soana.trickster.epilogue.commit': {'start': [(None, (), None, None)]},
                     'soana.trickster.epilogue.luck_late': {'start': [(None, (), None, None)]},
                     'soana.trickster.epilogue.luck_lost': {'start': [(None, (), None, None)]},
                     'soana.trickster.epilogue.declined': {'start': [(None, (), None, None)]},
                     'soana.trickster.epilogue.unfinished': {'start': [(None, (), None, None)]},
                     'soana.trickster.epilogue.by_your_hand': {'start': [(None, (), None, None)]},
                     'soana.trickster.epilogue.unbound': {'start': [(None, (), None, None)]},
                     'soana.trickster.epilogue.unvowed': {'start': [(None, (), None, None)]},
                     'soana.trickster.epilogue.friends': {'start': [(None, (), None, None)]},
                     'soana.trickster.epilogue.slack': {'start': [(None, (), None, None)]},
                     'soana.trickster.react.camellia_portion': {'start': [(None, (), None, None)]},
                     'soana.trickster.react.camellia_knot': {'start': [(None, (), None, None)]},
                     'soana.trickster.react.ember_portion': {'start': [(None, (), None, None)]},
                     'soana.trickster.react.ember_luck': {'start': [(None, (), None, None)]},
                     'soana.trickster.react.ulbrig_knot': {'start': [(None, (), None, None)]},
                     'soana.trickster.react.ulbrig_luck': {'start': [(None, (), None, None)]}}}


class SoanaSaveCompatibilityTests(unittest.TestCase):
    def test_existing_scenes_nodes_and_choices_remain_in_order(self):
        for module in (soana_late_campaign, soana_trickster):
            expected = BASELINE[module.__name__.split('.')[-1]]
            self.assertEqual([s['Id'] for s in module.SCENES[:len(expected)]], list(expected))
            for event in module.SCENES[:len(expected)]:
                old_nodes = expected[event['Id']]
                self.assertEqual([n['Id'] for n in event['Nodes'][:len(old_nodes)]], list(old_nodes))
                for page in event['Nodes'][:len(old_nodes)]:
                    old_answers = old_nodes[page['Id']]
                    self.assertGreaterEqual(len(page['Choices']), len(old_answers))
                    for actual, previous in zip(page['Choices'], old_answers):
                        current = (actual.get('Next'), tuple(actual['Set']), actual.get('NativeNext'), actual.get('Check'))
                        self.assertEqual(current, previous, (event['Id'], page['Id']))


if __name__ == '__main__':
    unittest.main()
