// <auto-generated />
// Regenerate with: python managed-tests/fixtures/parent-ending-source/generate.py
#nullable disable
using System; using System.Collections.Generic; using System.Linq; using System.Reflection; using Kingmaker.ElementsSystem;
internal static class ParentEndingSourceFixtures
{
internal static Dictionary<string, ConditionsChecker> Build()
{ var result = new Dictionary<string, ConditionsChecker>();
{
var conditions = ConditionsBuilder.New().EtudeStatus(null, null, "9fc5161813f1497f8eaad1563ac54211", negate: false, null, true).EtudeStatus(null, null, "07ad18ffb08145b69522f8eee0230857", negate: false, null, true)
			.UseOr();
var conditions2 = ConditionsBuilder.New().AddOrAndLogic(conditions).EtudeStatus(null, null, "4a29c758798d47a1a32f506d1ca6081b", negate: false, null, true);
var conditions3 = ConditionsBuilder.New().EtudeStatus(null, null, "592dcdccbef043f58031fa234faf137a", negate: false, null, true);
var conditions4 = ConditionsBuilder.New().EtudeStatus(null, null, "592dcdccbef043f58031fa234faf137a", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions5 = ConditionsBuilder.New().EtudeStatus(null, null, "592dcdccbef043f58031fa234faf137a", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions6 = ConditionsBuilder.New().EtudeStatus(null, null, "592dcdccbef043f58031fa234faf137a", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions7 = ConditionsBuilder.New().EtudeStatus(null, null, "3d21fa8120d040338ec1d4b8461fa536", negate: false, null, true).EtudeStatus(null, null, "e94e751a522748cd9194979e2646d5ec", negate: true, null, true);
var conditions8 = ConditionsBuilder.New().AddOrAndLogic(conditions7).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions9 = ConditionsBuilder.New().AddOrAndLogic(conditions7).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions10 = ConditionsBuilder.New().AddOrAndLogic(conditions7).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions11 = ConditionsBuilder.New().AddOrAndLogic(conditions3, negate: true).AddOrAndLogic(conditions7, negate: true);
var conditions12 = ConditionsBuilder.New().AddOrAndLogic(conditions11).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions13 = ConditionsBuilder.New().AddOrAndLogic(conditions11).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions14 = ConditionsBuilder.New().AddOrAndLogic(conditions11).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
result["951e4432cf844a36a8a222b27589fb43"] = conditions2.Build(null);
result["26789d87b5a44ba988079b4842bad81c"] = conditions3.Build(null);
result["e87b43c31c1c4253a7137c7d6c05b246"] = conditions4.Build(null);
result["819314e916514a498a8e336371b4788e"] = conditions5.Build(null);
result["9bfbb3f217ca476cadbeffc4d389717d"] = conditions6.Build(null);
result["e0551b6120c94d70aa9d10a5fcc4ec86"] = conditions7.Build(null);
result["7edf5529523a4a9da520138783fdeb93"] = conditions8.Build(null);
result["d6b960c14e37492682de6284af1c5417"] = conditions9.Build(null);
result["19fd9027465f4cbebe949b26d04a2826"] = conditions10.Build(null);
result["84e26e3c483c4e7985ac656de08a5b05"] = conditions11.Build(null);
result["f5e580bedafc43f3acb6843fd71d8120"] = conditions12.Build(null);
result["59cf28c3824944fd88547bc61bc5cf62"] = conditions13.Build(null);
result["92162854b221413984468d2663ffcffb"] = conditions14.Build(null);
}
{
var conditions = ConditionsBuilder.New().EtudeStatus(null, null, "592dcdccbef043f58031fa234faf137a", negate: false, null, true).EtudeStatus(null, null, "9fc5161813f1497f8eaad1563ac54211", negate: true, null, true)
			.EtudeStatus(null, null, "07ad18ffb08145b69522f8eee0230857", negate: true, null, true);
var conditions2 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true);
var conditions3 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions4 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions5 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions6 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "4a78282987fd432595c8a62d363730d7", negate: false, null, true);
var conditions7 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "4a78282987fd432595c8a62d363730d7", negate: false, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions8 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "4a78282987fd432595c8a62d363730d7", negate: false, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions9 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "4a78282987fd432595c8a62d363730d7", negate: false, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions10 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "4a78282987fd432595c8a62d363730d7", negate: true, null, true);
var conditions11 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "4a78282987fd432595c8a62d363730d7", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions12 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "4a78282987fd432595c8a62d363730d7", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions13 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "4a78282987fd432595c8a62d363730d7", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions14 = ConditionsBuilder.New().EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: false, null, true);
var conditions15 = ConditionsBuilder.New().EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
result["6db8635856e74b6cac46330bd82b4ff5"] = conditions.Build(null);
result["417936bb80bc48f28e1f0cee032d9ab6"] = conditions2.Build(null);
result["6eba6f627ac34cf4955c89e5ad59e106"] = conditions3.Build(null);
result["a875684118e64d7ab29f70ca3460c365"] = conditions4.Build(null);
result["9a5eb7aff04943c28da2260aac68874e"] = conditions5.Build(null);
result["a259e48a6513439483a2d8f31ea7ff39"] = conditions6.Build(null);
result["9806218e467f41acb502b52160ab38dd"] = conditions7.Build(null);
result["cce5f180fbe7455989544c1c81428463"] = conditions8.Build(null);
result["829c837c76f6429fa01d3d2583069b35"] = conditions9.Build(null);
result["f9ec524d3ff04b999afc1e8bfe50ae4e"] = conditions10.Build(null);
result["3b8d47b3c9694002aff26510ac4dedf0"] = conditions11.Build(null);
result["51104e1c8755436e8aa290a6cedfcb3a"] = conditions12.Build(null);
result["fb32a8f9c464496abe90307c68ec271e"] = conditions13.Build(null);
result["222f780971834ea28357b2533f921e9d"] = conditions14.Build(null);
result["a77e415c6eb44d719839e07a3f164d87"] = conditions15.Build(null);
}
{
var conditions = ConditionsBuilder.New().EtudeStatus(null, null, "e94e751a522748cd9194979e2646d5ec", negate: false, null, true).EtudeStatus(null, null, "3d21fa8120d040338ec1d4b8461fa536", negate: false, null, true);
var conditions2 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true);
var conditions3 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions4 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions5 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions6 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true);
var conditions7 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions8 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions9 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions10 = ConditionsBuilder.New().EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: false, null, true);
var conditions11 = ConditionsBuilder.New().EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions12 = ConditionsBuilder.New().EtudeStatus(null, null, "1e6ca1514807446ea2fddd65e4f5bcc8", negate: false, null, true);
result["8df5edb6f69040c69d7da78d2bf20cb6"] = conditions.Build(null);
result["5570b60904f34d29ab925ef19757f024"] = conditions2.Build(null);
result["0a8411c2cb0a44f1ab317ed425f6ec94"] = conditions3.Build(null);
result["5ab5c6a3c62b4f2ba88053cbbbc47737"] = conditions4.Build(null);
result["dc14cdafb9fa43e8bc3b0816626b3dbe"] = conditions5.Build(null);
result["2741346e336e4c3899748e51bf103460"] = conditions6.Build(null);
result["acb0d15ef71c410484b7c37b270e30fe"] = conditions7.Build(null);
result["f37b7a5fcff84551b86ecbba823e2fa5"] = conditions8.Build(null);
result["982627a0bbd34fe4b16b5b078e56355a"] = conditions9.Build(null);
result["02fd8486e8e44191ab01cf914087a00e"] = conditions10.Build(null);
result["67e3bb3b649d42a4a84115f3c7ac6bf1"] = conditions11.Build(null);
result["2c5edf138eac4848940d8ebbafe1535d"] = conditions12.Build(null);
}
{
var conditions = ConditionsBuilder.New().EtudeStatus(null, null, "e94e751a522748cd9194979e2646d5ec", negate: true, null, true).EtudeStatus(null, null, "3d21fa8120d040338ec1d4b8461fa536", negate: false, null, true);
var conditions2 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true);
var conditions3 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions4 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions5 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions6 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true);
var conditions7 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions8 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions9 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions10 = ConditionsBuilder.New().EtudeStatus(null, null, "1e6ca1514807446ea2fddd65e4f5bcc8", negate: false, null, true);
result["5a5865ceca0e42049288351a76b18ba9"] = conditions.Build(null);
result["a7d2f947a47e40bc9d7c0c24da1b9be3"] = conditions2.Build(null);
result["286434b491b74174a97dfd2d7344f57a"] = conditions3.Build(null);
result["784575a522e64ad58f2171abcb073d0c"] = conditions4.Build(null);
result["5db846019acd46ef83f12be220727f50"] = conditions5.Build(null);
result["1f1d17818c9f4057be26e47d1632e2c6"] = conditions6.Build(null);
result["3d4137f1cf98459f996ef1da83737cdb"] = conditions7.Build(null);
result["9e3bd8247f0c40eba62368fe2912bb84"] = conditions8.Build(null);
result["18d22b6258a24fe29dd9d0ea4235432e"] = conditions9.Build(null);
result["8c6accdc29f54a428d3a59786c1c856d"] = conditions10.Build(null);
}
{
var conditions = ConditionsBuilder.New().EtudeStatus(null, null, "58557969a797441983022c8ba0400400", negate: false, null, true).EtudeStatus(null, null, "3d21fa8120d040338ec1d4b8461fa536", negate: true, null, true);
var conditions2 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true);
var conditions3 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions4 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions5 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions6 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true);
var conditions7 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions8 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions9 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions10 = ConditionsBuilder.New().EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: false, null, true);
var conditions11 = ConditionsBuilder.New().EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
result["126762ac92364ac5bdec69c6e3fdfd1a"] = conditions.Build(null);
result["7d970543808f428380fb1042b32f896e"] = conditions2.Build(null);
result["a1774d0a9fb34fd2ac58abc1c6db55bd"] = conditions3.Build(null);
result["d47984953fc74c488ef0a02588bde92b"] = conditions4.Build(null);
result["b474eb4460cb42729be2717d05e7d42b"] = conditions5.Build(null);
result["f6d5d9bfdf1442528be5e6d81b656ac2"] = conditions6.Build(null);
result["2cd9538f67f7414d808d9032386f6be9"] = conditions7.Build(null);
result["8009e775a3a343c79ef4e40d72bc5e6a"] = conditions8.Build(null);
result["5b0a132d97404072b3d664899871d7b7"] = conditions9.Build(null);
result["a200043a0b9a4d97a0da3fea0c0890a1"] = conditions10.Build(null);
result["0b1b31d7125547219daa747eba45a063"] = conditions11.Build(null);
}
{
var conditions = ConditionsBuilder.New().EtudeStatus(null, null, "e303c58d307849cd892fa5810124da92", negate: false, null, true);
var conditions2 = ConditionsBuilder.New().EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions3 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions4 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions5 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
var conditions6 = ConditionsBuilder.New().EtudeStatus(null, null, "c6935ff7cbfd4aed8ac479e94e66918d", negate: true, null, true).EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true)
			.EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true)
			.EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true);
result["01677da8df6e42c6b4803ceef524b1fe"] = conditions.Build(null);
result["56f4e95390ec472b855e759fbc548b81"] = ConditionsBuilder.New().Build(null);
result["85b479a3da8a4fa6b602fedf89201695"] = conditions2.Build(null);
result["64afcd565e044e53977e1878444f4ee1"] = conditions3.Build(null);
result["b9e2550bc7244f6c8480106b41667d96"] = conditions4.Build(null);
result["bb49f54dc0a547c287238b5d7d8489b3"] = conditions5.Build(null);
result["5831af75932d43ed902a2d8def2adf3d"] = conditions6.Build(null);
}
{
var conditions = ConditionsBuilder.New().EtudeStatus(null, null, "a87da83417ff4be28c9ccfaf9b154e96", negate: false, null, true);
var conditions2 = ConditionsBuilder.New().EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions3 = ConditionsBuilder.New().EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: true, null, true).EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true)
			.EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true);
var conditions4 = ConditionsBuilder.New().EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true).EtudeStatus(null, null, "b5c19cd01e364df99f6c946c7da14751", negate: false, null, true)
			.EtudeStatus(null, null, "381a296094804761af0893d2e70dc2df", negate: true, null, true);
result["9c5c5825bf3245d0ae763c6e69ecdc38"] = conditions.Build(null);
result["7b56a6e716ce4aacaae1060fb33c3a0f"] = ConditionsBuilder.New().Build(null);
result["8399dbc5987b462594b2b4168764e269"] = conditions2.Build(null);
result["d6714bd8d48e425d862f854018cb123c"] = conditions3.Build(null);
result["ff2042ad95e14b73a5f75f2cfd84b5e4"] = conditions4.Build(null);
}
{
var conditions = ConditionsBuilder.New().DialogSeen("91a3699b2b12496db23b33dad6746d31").AnswerSelected("b192e1e211654bcca27924c12e8aa617", null, negate: true);
var conditions2 = ConditionsBuilder.New().EtudeStatus(null, null, "4a29c758798d47a1a32f506d1ca6081b", negate: false, null, true);
var conditions3 = ConditionsBuilder.New().EtudeStatus(null, null, "4a29c758798d47a1a32f506d1ca6081b", negate: false, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
var conditions4 = ConditionsBuilder.New().EtudeStatus(null, null, "4a29c758798d47a1a32f506d1ca6081b", negate: true, null, true);
var conditions5 = ConditionsBuilder.New().EtudeStatus(null, null, "4a29c758798d47a1a32f506d1ca6081b", negate: true, null, true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
result["3792457f35734d75a4d4b53055f7f5d0"] = conditions.Build(null);
result["dce10a002c5c4e83838d1b85096b2d15"] = conditions2.Build(null);
result["1980e50e5e204431bf643fbad487909f"] = conditions3.Build(null);
result["bf05f030b0044487bca43db8296dfe31"] = conditions4.Build(null);
result["c47829fba057400c8e0279990be3d25e"] = conditions5.Build(null);
}
{
var conditions = ConditionsBuilder.New().DialogSeen("91a3699b2b12496db23b33dad6746d31").AnswerSelected("b192e1e211654bcca27924c12e8aa617", null, negate: true);
var conditions2 = ConditionsBuilder.New().FlagUnlocked("a8b030ebca6c9744bac633cff609b698").EtudeStatus(null, null, "592dcdccbef043f58031fa234faf137a", negate: true, null, true)
			.EtudeStatus(null, null, "4a29c758798d47a1a32f506d1ca6081b", negate: false, null, true);
var conditions3 = ConditionsBuilder.New().FlagUnlocked("a8b030ebca6c9744bac633cff609b698").EtudeStatus(null, null, "592dcdccbef043f58031fa234faf137a", negate: false, null, true);
result["6bf016f775734c3eb4f287c29c59e9f9"] = conditions.Build(null);
result["685e559def61431f81cd18f6b52dc582"] = ConditionsBuilder.New().Build(null);
result["e5ccfcbbc43742ffbfdd49214f42e123"] = conditions2.Build(null);
result["52cf9efdb6b9447a8c0e52e314fec722"] = conditions3.Build(null);
}
{
var conditions = ConditionsBuilder.New().DialogSeen("91a3699b2b12496db23b33dad6746d31").AnswerSelected("b192e1e211654bcca27924c12e8aa617", null, negate: true);
var conditions2 = ConditionsBuilder.New().AddOrAndLogic(conditions, negate: true).EtudeStatus(null, null, "71f85264d9064074f9cf74999ecbffa9", negate: false, null, true);
result["5c95d8e3fa4f3b44896914987cb04b0b"] = conditions2.Build(null);
}
result["5787f92575364c1459df8f075676c2db"] = ConditionsBuilder.New().Build(null);
return result; }
internal static ActionList PageActions()
{
return ActionsBuilder.New().MarkCuesSeen("951e4432cf844a36a8a222b27589fb43").MarkCuesSeen("6db8635856e74b6cac46330bd82b4ff5")
			.MarkCuesSeen("8df5edb6f69040c69d7da78d2bf20cb6")
			.MarkCuesSeen("5a5865ceca0e42049288351a76b18ba9")
			.MarkCuesSeen("126762ac92364ac5bdec69c6e3fdfd1a")
			.MarkCuesSeen("01677da8df6e42c6b4803ceef524b1fe")
			.MarkCuesSeen("9c5c5825bf3245d0ae763c6e69ecdc38")
			.MarkCuesSeen("3792457f35734d75a4d4b53055f7f5d0").Build(null);
}
// Headless reconstruction of extracted expressions using actual native condition types.
internal class ConditionsBuilder {
 readonly List<Condition> conditions=new List<Condition>(); bool useOr;
 internal static ConditionsBuilder New()=>new ConditionsBuilder();
 internal static object Reference(Type type,string text){var result=Activator.CreateInstance(type);typeof(Kingmaker.Blueprints.BlueprintReferenceBase).GetField("deserializedGuid",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(result,Kingmaker.Blueprints.BlueprintGuid.Parse(text));return result;}
 ConditionsBuilder Add(Condition c){conditions.Add(c);return this;}
 static void Ref(object c,string field,string id){var f=c.GetType().GetField(field,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic);f.SetValue(c,Reference(f.FieldType,id));}
 internal ConditionsBuilder UseOr(){useOr=true;return this;}
 internal ConditionsBuilder AddOrAndLogic(ConditionsBuilder b,bool negate=false)=>Add(new Kingmaker.Designers.EventConditionActionSystem.Conditions.OrAndLogic{ConditionsChecker=b.Build(null),Not=negate});
 internal ConditionsBuilder EtudeStatus(bool? completed,bool? completionInProgress,string etude,bool negate=false,bool? notStarted=null,bool? playing=null,bool? started=null){
 var c=new Kingmaker.Designers.EventConditionActionSystem.Conditions.EtudeStatus{Not=negate};Ref(c,"m_Etude",etude);
 if(completed.HasValue)c.Completed=completed.Value;if(completionInProgress.HasValue)c.CompletionInProgress=completionInProgress.Value;if(notStarted.HasValue)c.NotStarted=notStarted.Value;if(playing.HasValue)c.Playing=playing.Value;if(started.HasValue)c.Started=started.Value;return Add(c);}
 internal ConditionsBuilder DialogSeen(string dialog,bool negate=false){var c=new Kingmaker.Assets.Designers.EventConditionActionSystem.Conditions.DialogSeen{Not=negate};Ref(c,"m_Dialog",dialog);return Add(c);}
 internal ConditionsBuilder AnswerSelected(string answer,bool? currentDialog=null,bool negate=false){var c=new Kingmaker.Designers.EventConditionActionSystem.Conditions.AnswerSelected{Not=negate};if(currentDialog.HasValue)c.CurrentDialog=currentDialog.Value;Ref(c,"m_Answer",answer);return Add(c);}
 internal ConditionsBuilder FlagUnlocked(string conditionFlag,bool? exceptSpecifiedValues=null,bool negate=false,List<int> specifiedValues=null){var c=new Kingmaker.Designers.EventConditionActionSystem.Conditions.FlagUnlocked{Not=negate};if(exceptSpecifiedValues.HasValue)c.ExceptSpecifiedValues=exceptSpecifiedValues.Value;if(specifiedValues!=null)c.SpecifiedValues=specifiedValues;Ref(c,"m_ConditionFlag",conditionFlag);return Add(c);}
 internal ConditionsChecker Build(object validator)=>new ConditionsChecker{Conditions=conditions.ToArray(),Operation=useOr?Operation.Or:Operation.And};
}
internal class ActionsBuilder {
 readonly List<GameAction> actions=new List<GameAction>();
 internal static ActionsBuilder New()=>new ActionsBuilder();
 internal ActionsBuilder MarkCuesSeen(params string[] cues){var c=new Kingmaker.Designers.EventConditionActionSystem.Actions.MarkCuesSeen();typeof(Kingmaker.Designers.EventConditionActionSystem.Actions.MarkCuesSeen).GetField("m_Cues",BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public).SetValue(c,cues.Select(s=>(Kingmaker.Blueprints.BlueprintCueBaseReference)ConditionsBuilder.Reference(typeof(Kingmaker.Blueprints.BlueprintCueBaseReference),s)).ToArray());actions.Add(c);return this;}
 internal ActionList Build(object validator)=>new ActionList{Actions=actions.ToArray()};
}
}
